// Central product catalog — all prices and IDs synced with Stripe
export const AI_PRODUCTS = [
  {
    product_id: "prod_UNi5RHiKNSTfQl",
    name: "Instant Lead Response",
    subtitle: "SMS",
    description: "AI sends a personalized SMS to every new lead within seconds — 24/7, even at 2am.",
    setup_fee: 297,
    monthly_fee: 97,
    setup_price_id: "price_1TOwfiB9GU5ysJqEcmQHl3gE",
    monthly_price_id: "price_1TOwfiB9GU5ysJqE20FYUfVc",
    icon: "⚡",
    category: "Response",
    highlights: ["Responds in under 4 seconds", "Works 24/7 automatically", "Personalized per lead source"],
    popular: true,
  },
  {
    product_id: "prod_UNi5QL0bQl98If",
    name: "Missed Call Text-Back",
    subtitle: "Never lose a lead",
    description: "Every missed call gets an automatic text-back within 60 seconds. Zero leads lost.",
    setup_fee: 197,
    monthly_fee: 67,
    setup_price_id: "price_1TOwfiB9GU5ysJqEJuEDhpKS",
    monthly_price_id: "price_1TOwfiB9GU5ysJqE8knUfswZ",
    icon: "📞",
    category: "Response",
    highlights: ["60-second auto text-back", "Keeps lead engaged", "Works while you're with clients"],
  },
  {
    product_id: "prod_UNi5N0l5MtaV0R",
    name: "14-Day Nurture Sequence",
    subtitle: "SMS + Email",
    description: "Multi-step SMS and email follow-up keeps leads warm and moving toward a booking for 14 days.",
    setup_fee: 397,
    monthly_fee: 127,
    setup_price_id: "price_1TOwfiB9GU5ysJqEtwQAmCuN",
    monthly_price_id: "price_1TOwfiB9GU5ysJqEsoZmFl6D",
    icon: "🔄",
    category: "Follow-Up",
    highlights: ["14-day automated sequence", "Smart timing per behavior", "SMS + email combined"],
    popular: true,
  },
  {
    product_id: "prod_UNi5fLL2SyJJdP",
    name: "AI Booking Agent",
    subtitle: "Auto-schedule",
    description: "Guided booking flow that converts inquiries to confirmed calendar appointments automatically.",
    setup_fee: 497,
    monthly_fee: 147,
    setup_price_id: "price_1TOwfiB9GU5ysJqEij8Qq9rd",
    monthly_price_id: "price_1TOwfiB9GU5ysJqEKhYvS71r",
    icon: "📅",
    category: "Booking",
    highlights: ["Zero manual scheduling", "Direct calendar sync", "Confirmation sent instantly"],
    popular: true,
  },
  {
    product_id: "prod_UNi5PWv05ECzXI",
    name: "Old Lead Reactivation",
    subtitle: "Recover revenue",
    description: "Proven reactivation campaigns turn dormant contacts into fresh revenue opportunities.",
    setup_fee: 297,
    monthly_fee: 97,
    setup_price_id: "price_1TOwfiB9GU5ysJqExMxwfoFr",
    monthly_price_id: "price_1TOwfiB9GU5ysJqEfsJEvPcI",
    icon: "💰",
    category: "Revenue",
    highlights: ["Avg. $4k recovered/mo", "Proven re-engagement copy", "Targets dormant contacts"],
  },
  {
    product_id: "prod_UNi5dvOUm6Fi9i",
    name: "Review Request Automation",
    subtitle: "Google & Yelp",
    description: "Automatically request Google and Yelp reviews from happy customers after their appointment.",
    setup_fee: 197,
    monthly_fee: 67,
    setup_price_id: "price_1TOwfiB9GU5ysJqEO8byuwlT",
    monthly_price_id: "price_1TOwfiB9GU5ysJqEryd66HuE",
    icon: "⭐",
    category: "Reputation",
    highlights: ["Auto-triggered post-visit", "Google & Yelp integration", "Boost star rating fast"],
  },
  {
    product_id: "prod_UNi5aQjPk58U4o",
    name: "AI Email Follow-Up",
    subtitle: "Sequence",
    description: "Smart email sequences that nurture leads and clients with personalized, timely messages.",
    setup_fee: 297,
    monthly_fee: 97,
    setup_price_id: "price_1TOwfiB9GU5ysJqEJcZwnVFL",
    monthly_price_id: "price_1TOwfiB9GU5ysJqExHsLIEtN",
    icon: "📧",
    category: "Follow-Up",
    highlights: ["Personalized per lead", "Smart send timing", "Tracks opens & clicks"],
  },
  {
    product_id: "prod_UNi5ybXQSG6QkX",
    name: "Missed Appointment Recovery",
    subtitle: "Rebook no-shows",
    description: "Automatically re-engage no-shows with recovery sequences to rebook lost appointments.",
    setup_fee: 247,
    monthly_fee: 77,
    setup_price_id: "price_1TOwfiB9GU5ysJqEO8w24UTX",
    monthly_price_id: "price_1TOwfiB9GU5ysJqE1M9PoI15",
    icon: "🔁",
    category: "Booking",
    highlights: ["Targets no-shows instantly", "Multi-step rebook sequence", "Fills empty calendar slots"],
  },
  {
    product_id: "prod_UNi5Df5KWsS4lW",
    name: "New Client Onboarding",
    subtitle: "Flow",
    description: "Automated welcome sequences and onboarding messages that delight new clients from day one.",
    setup_fee: 347,
    monthly_fee: 107,
    setup_price_id: "price_1TOwfiB9GU5ysJqEJ7XM5LB6",
    monthly_price_id: "price_1TOwfiB9GU5ysJqEpL7Tbjzm",
    icon: "🎉",
    category: "Retention",
    highlights: ["Welcome flow on signup", "Sets expectations clearly", "Reduces churn from day 1"],
  },
  {
    product_id: "prod_UNi53DY2nkRTuM",
    name: "Social DM Auto-Responder",
    subtitle: "Instagram & Facebook",
    description: "AI instantly replies to Instagram and Facebook DMs, converting social followers into leads.",
    setup_fee: 397,
    monthly_fee: 127,
    setup_price_id: "price_1TOwfiB9GU5ysJqE3mAZpu43",
    monthly_price_id: "price_1TOwfiB9GU5ysJqEfV7uVJLb",
    icon: "💬",
    category: "Social",
    highlights: ["Instagram + Facebook DMs", "Converts followers to leads", "24/7 AI response"],
  },
  {
    product_id: "prod_UNi5Li4ZFZGRIc",
    name: "AI Reputation Manager",
    subtitle: "Reviews & ratings",
    description: "Monitor and respond to reviews across platforms automatically to protect and grow your reputation.",
    setup_fee: 447,
    monthly_fee: 137,
    setup_price_id: "price_1TOwfiB9GU5ysJqEEvf0RdVG",
    monthly_price_id: "price_1TOwfiB9GU5ysJqEkzPf9zrt",
    icon: "🛡️",
    category: "Reputation",
    highlights: ["Multi-platform monitoring", "Auto-response to reviews", "Alerts on negative reviews"],
  },
  {
    product_id: "prod_UNi5nfHZ3XKzzZ",
    name: "Lead Scoring & Qualification",
    subtitle: "AI-powered",
    description: "AI scores and qualifies every lead so you only spend time on the most likely to convert.",
    setup_fee: 547,
    monthly_fee: 167,
    setup_price_id: "price_1TOwfiB9GU5ysJqELMl0Jlbf",
    monthly_price_id: "price_1TOwfiB9GU5ysJqEesWHeFVY",
    icon: "🎯",
    category: "Intelligence",
    highlights: ["0–100 AI quality score", "Auto-prioritizes hot leads", "Filters time-wasters out"],
  },
];

export const CATEGORIES = ["All", "Response", "Follow-Up", "Booking", "Revenue", "Reputation", "Social", "Retention", "Intelligence"];