export const PHASE_D_SOURCE = {
  issue: 1382,
  title: "Phase D architecture - Administration, billing, permissions, integrations, security, and support",
  constraints: [
    "Static review preparation only",
    "No production integration or live financial claims",
    "No merge or rollout without Worker #2 authorization",
  ],
};

export const ENTERPRISE_ADMIN_ROLES = [
  "Owner",
  "Admin",
  "Manager",
  "Sales",
  "Marketing",
  "Support",
  "Analyst",
  "Viewer",
];

export const ENTERPRISE_ADMIN_PERMISSIONS = [
  "View",
  "Create",
  "Edit",
  "Delete",
  "Approve",
  "Export",
  "Manage",
];

export const ENTERPRISE_ADMIN_SCOPES = [
  "Organization",
  "Client",
  "Location",
];

const ALL_PERMISSIONS = ENTERPRISE_ADMIN_PERMISSIONS;
const VIEW_ONLY = ["View"];
const VIEW_EXPORT = ["View", "Export"];
const OPERATE = ["View", "Create", "Edit"];
const OPERATE_EXPORT = ["View", "Create", "Edit", "Export"];
const OPERATE_APPROVE_EXPORT = ["View", "Create", "Edit", "Approve", "Export"];

export const ROLE_SCOPE_PERMISSIONS = {
  Owner: {
    Organization: ALL_PERMISSIONS,
    Client: ALL_PERMISSIONS,
    Location: ALL_PERMISSIONS,
  },
  Admin: {
    Organization: ["View", "Create", "Edit", "Approve", "Export", "Manage"],
    Client: ALL_PERMISSIONS,
    Location: ALL_PERMISSIONS,
  },
  Manager: {
    Organization: VIEW_EXPORT,
    Client: OPERATE_APPROVE_EXPORT,
    Location: OPERATE_APPROVE_EXPORT,
  },
  Sales: {
    Organization: VIEW_ONLY,
    Client: OPERATE_EXPORT,
    Location: ["View", "Create", "Edit"],
  },
  Marketing: {
    Organization: ["View", "Create", "Edit", "Export"],
    Client: ["View", "Create", "Edit", "Export"],
    Location: OPERATE_EXPORT,
  },
  Support: {
    Organization: VIEW_ONLY,
    Client: OPERATE,
    Location: OPERATE,
  },
  Analyst: {
    Organization: VIEW_EXPORT,
    Client: VIEW_EXPORT,
    Location: VIEW_EXPORT,
  },
  Viewer: {
    Organization: VIEW_ONLY,
    Client: VIEW_ONLY,
    Location: VIEW_ONLY,
  },
};

export const ROLE_PERMISSION_MATRIX = ENTERPRISE_ADMIN_ROLES.flatMap((role) =>
  ENTERPRISE_ADMIN_SCOPES.map((scope) => ({
    role,
    scope,
    permissions: ROLE_SCOPE_PERMISSIONS[role][scope],
  })),
);

export const ENTERPRISE_STATE_CONTRACTS = {
  review: [
    "Loading",
    "Empty",
    "Current",
    "Partial",
    "Stale",
    "Delayed",
    "Unavailable",
    "Restricted",
    "Unknown",
    "Recoverable Error",
  ],
  integrations: [
    "Connected",
    "Verifying",
    "Healthy",
    "Degraded",
    "Disconnected",
    "Permission Required",
    "Unknown",
    "Stale",
    "Unsupported",
  ],
  billing: [
    "Active",
    "Trial",
    "Past Due",
    "Cancelled",
    "Scheduled Change",
    "Payment Failed",
    "Incomplete",
    "Unavailable",
    "Permission Restricted",
  ],
  usage: [
    "Measured",
    "Estimated",
    "Delayed",
    "Unavailable",
    "Out Of Date",
  ],
  notifications: [
    "Enabled",
    "Paused",
    "Digest",
    "Escalation Only",
    "Opted Out",
    "Permission Restricted",
    "Unknown",
  ],
  security: [
    "Recognized",
    "New Device",
    "Revoked",
    "Expired",
    "Permission Change",
    "Alert",
    "Blocked",
    "Unknown",
  ],
  support: [
    "Open",
    "Waiting On Client",
    "Escalated",
    "Monitoring",
    "Resolved",
    "SLA At Risk",
    "Unknown",
  ],
};

export const ENTERPRISE_SETTINGS_ROUTES = [
  {
    id: "organization",
    path: "/settings/organization",
    label: "Organization",
    system: "Organization Settings",
    priority: 1,
    navGroup: "Administration",
  },
  {
    id: "team",
    path: "/settings/team",
    label: "Team",
    system: "Team Management",
    priority: 2,
    navGroup: "Administration",
  },
  {
    id: "roles",
    path: "/settings/roles",
    label: "Roles",
    system: "Roles and Permissions",
    priority: 2,
    navGroup: "Administration",
  },
  {
    id: "integrations",
    path: "/settings/integrations",
    label: "Integrations",
    system: "Integration Center",
    priority: 3,
    navGroup: "Operations",
  },
  {
    id: "billing",
    path: "/settings/billing",
    label: "Billing",
    system: "Billing and Subscription",
    priority: 4,
    navGroup: "Commerce",
  },
  {
    id: "usage",
    path: "/settings/usage",
    label: "Usage",
    system: "Usage and Entitlements",
    priority: 5,
    navGroup: "Commerce",
  },
  {
    id: "notifications",
    path: "/settings/notifications",
    label: "Notifications",
    system: "Notification Preferences",
    priority: 6,
    navGroup: "Operations",
  },
  {
    id: "security",
    path: "/settings/security",
    label: "Security",
    system: "Security Activity",
    priority: 7,
    navGroup: "Risk",
  },
  {
    id: "audit",
    path: "/settings/audit",
    label: "Audit",
    system: "Audit History",
    priority: 7,
    navGroup: "Risk",
  },
  {
    id: "support",
    path: "/settings/support",
    label: "Support",
    system: "Support and Escalation Center",
    priority: 8,
    navGroup: "Operations",
  },
];

const COMMON_REVIEW_STATES = [
  "Loading",
  "Empty",
  "Current",
  "Partial",
  "Stale",
  "Delayed",
  "Unavailable",
  "Restricted",
  "Unknown",
  "Recoverable Error",
];

export const ENTERPRISE_SETTINGS_SECTIONS = {
  organization: {
    title: "Organization Settings",
    eyebrow: "Administration",
    summary: "Company profile, locations, domains, brand controls, and account preferences.",
    stateKeys: ["review"],
    sourceSemantics: {
      source: "Phase D review fixture mapped to AdminSettings, ClientProject, and future Organization records",
      freshness: "Static foundation, not a production read",
      scope: "Organization",
      verification: "Requires Worker #2 source binding before any saved setting is trusted",
    },
    panels: [
      {
        id: "company",
        title: "Company",
        status: "Current",
        scope: "Organization",
        source: "Organization profile fixture",
        freshness: "Prepared",
        verification: "Business identity review required",
        consequence: "Incorrect legal or public identity can break contracts, invoices, and trust copy.",
        nextAction: "Bind company profile to the approved organization source.",
        fields: [
          ["Display name", "ClientSurge Systems"],
          ["Legal name", "Pending verification"],
          ["Primary industry", "Local service automation"],
        ],
      },
      {
        id: "locations",
        title: "Locations",
        status: "Partial",
        scope: "Location",
        source: "Location fixture",
        freshness: "Prepared",
        verification: "Needs canonical location entity",
        consequence: "Routing, timezone, and reporting can drift when location ownership is unclear.",
        nextAction: "Create scoped location source and attach assignments.",
        fields: [
          ["Primary timezone", "America/Phoenix"],
          ["Operating region", "United States"],
          ["Location count", "Fixture only"],
        ],
      },
      {
        id: "domains",
        title: "Domains",
        status: "Stale",
        scope: "Organization",
        source: "Domain readiness fixture",
        freshness: "Needs live DNS and edge proof",
        verification: "Requires public route and security header validation",
        consequence: "Unverified domains can make launch proof, login callbacks, and email trust unreliable.",
        nextAction: "Link domain status to Cloudflare and Base44 publish proof.",
        fields: [
          ["Primary domain", "clientsurgesystems.com"],
          ["Security headers", "Not verified in this view"],
          ["Return path", "/settings/security#audit-events"],
        ],
      },
      {
        id: "brand",
        title: "Brand",
        status: "Current",
        scope: "Organization",
        source: "Design token fixture",
        freshness: "Prepared",
        verification: "Needs approved brand asset registry",
        consequence: "Uncontrolled brand edits can create public trust and email consistency drift.",
        nextAction: "Bind approved logos, colors, and sender identity to one asset source.",
        fields: [
          ["Primary accent", "Commerce Blue reserved for purchase actions"],
          ["Logo set", "Prepared"],
          ["Email sender brand", "Restricted until verified"],
        ],
      },
      {
        id: "preferences",
        title: "Preferences",
        status: "Current",
        scope: "Organization",
        source: "Preference fixture",
        freshness: "Prepared",
        verification: "Needs persisted preferences entity",
        consequence: "Default timezone, language, and approval settings affect downstream workflows.",
        nextAction: "Wire preference saves through audited settings mutation.",
        fields: [
          ["Timezone", "America/Phoenix"],
          ["Default approval", "Owner approval required"],
          ["Data display", "Proof gated"],
        ],
      },
    ],
    safeguards: [
      "Domain removal requires Owner approval and a typed confirmation.",
      "Brand sender changes require audit capture before activation.",
      "Organization deletion is unavailable in Phase D foundation.",
    ],
    auditEvents: [
      "organization.company.updated",
      "organization.domain.verified",
      "organization.brand.changed",
    ],
    acceptance: [
      "Company, Locations, Domains, Brand, and Preferences are visible at /settings/organization.",
      "Each panel states source, freshness, scope, verification, business consequence, and next action.",
    ],
  },
  team: {
    title: "Team Management",
    eyebrow: "Administration",
    summary: "Users, invites, teams, assignments, and activity with explicit organization, client, and location scope.",
    stateKeys: ["review"],
    sourceSemantics: {
      source: "Phase D review fixture mapped to future membership and invite records",
      freshness: "Static foundation, not a production read",
      scope: "Organization, Client, Location",
      verification: "Requires identity provider and invitation source binding",
    },
    panels: [
      {
        id: "users",
        title: "Users",
        status: "Current",
        scope: "Organization",
        source: "Membership fixture",
        freshness: "Prepared",
        verification: "Needs authenticated membership source",
        consequence: "Wrong user state can expose client data or block fulfillment work.",
        nextAction: "Bind user table to membership records with role and scope filters.",
        fields: [
          ["Active users", "Fixture only"],
          ["Pending review", "Role scope required"],
          ["Locked users", "Shown as restricted"],
        ],
      },
      {
        id: "invites",
        title: "Invites",
        status: "Delayed",
        scope: "Organization",
        source: "Invite fixture",
        freshness: "Prepared",
        verification: "Needs invite delivery and expiration proof",
        consequence: "Expired or mis-scoped invites can create onboarding delays or access risk.",
        nextAction: "Attach invite lifecycle events and resend safeguards.",
        fields: [
          ["Pending invites", "Fixture only"],
          ["Expiration", "7 days proposed"],
          ["Approval", "Admin or Owner"],
        ],
      },
      {
        id: "teams",
        title: "Teams",
        status: "Partial",
        scope: "Client",
        source: "Team fixture",
        freshness: "Prepared",
        verification: "Needs client-team membership source",
        consequence: "Assignment ownership gets ambiguous without team boundaries.",
        nextAction: "Define teams as organization-scoped groups with client overlays.",
        fields: [
          ["Ops team", "Prepared"],
          ["Sales team", "Prepared"],
          ["Support team", "Prepared"],
        ],
      },
      {
        id: "assignments",
        title: "Assignments",
        status: "Current",
        scope: "Client, Location",
        source: "Assignment fixture",
        freshness: "Prepared",
        verification: "Needs assignment write audit",
        consequence: "Clients can fall through handoff when assignment changes are not tracked.",
        nextAction: "Connect owner, backup, and escalation assignment records.",
        fields: [
          ["Primary owner", "Required"],
          ["Backup owner", "Recommended"],
          ["Location override", "Scoped"],
        ],
      },
      {
        id: "activity",
        title: "Activity",
        status: "Current",
        scope: "Organization",
        source: "Activity fixture",
        freshness: "Prepared",
        verification: "Needs actor and outcome preservation",
        consequence: "Access changes cannot be investigated without durable activity.",
        nextAction: "Send invite, role, and assignment events to audit history.",
        fields: [
          ["Actor", "Required"],
          ["Outcome", "Required"],
          ["Source", "Required"],
        ],
      },
    ],
    safeguards: [
      "Invite cancellation and resend actions must show target email, role, and scope before execution.",
      "Role changes require reason capture and audit event write.",
      "Assignment removals require a replacement owner or escalation path.",
    ],
    auditEvents: [
      "team.user.invited",
      "team.user.deactivated",
      "team.assignment.changed",
    ],
    acceptance: [
      "Users, Invites, Teams, Assignments, and Activity are visible at /settings/team.",
      "Team activity preserves actor, action, target, timestamp, source, and outcome semantics.",
    ],
  },
  roles: {
    title: "Roles and Permissions",
    eyebrow: "Administration",
    summary: "RBAC matrix for Owner, Admin, Manager, Sales, Marketing, Support, Analyst, and Viewer.",
    stateKeys: ["review"],
    sourceSemantics: {
      source: "Phase D RBAC contract",
      freshness: "Static foundation, not a production read",
      scope: "Organization, Client, Location",
      verification: "Requires enforcement in protected routes, backend functions, and data access filters",
    },
    panels: [
      {
        id: "rbac",
        title: "RBAC Matrix",
        status: "Current",
        scope: "Organization, Client, Location",
        source: "Role permission contract",
        freshness: "Prepared",
        verification: "Needs Worker #3 enforcement mapping",
        consequence: "Implicit permissions create launch risk for billing, exports, and client data.",
        nextAction: "Map this matrix to route guards and backend authorization checks.",
        fields: [
          ["Roles", ENTERPRISE_ADMIN_ROLES.join(", ")],
          ["Permissions", ENTERPRISE_ADMIN_PERMISSIONS.join(", ")],
          ["Scopes", ENTERPRISE_ADMIN_SCOPES.join(", ")],
        ],
      },
      {
        id: "approval",
        title: "Approval Rules",
        status: "Partial",
        scope: "Organization",
        source: "Approval fixture",
        freshness: "Prepared",
        verification: "Needs policy engine",
        consequence: "High-risk actions can bypass review without approval gates.",
        nextAction: "Attach approval policy to billing, security, exports, and destructive actions.",
        fields: [
          ["Billing changes", "Owner or Admin approval"],
          ["Exports", "Manager and above"],
          ["Deletes", "Owner approval for organization scope"],
        ],
      },
    ],
    safeguards: [
      "Owner role cannot be removed when it is the final organization owner.",
      "Delete and Manage permissions require explicit scope selection.",
      "Permission changes require reason capture and audit event write.",
    ],
    auditEvents: [
      "rbac.role.changed",
      "rbac.permission.granted",
      "rbac.permission.revoked",
    ],
    acceptance: [
      "All eight roles, seven permissions, and three scopes are represented.",
      "Role changes preserve actor, action, target, timestamp, source, and outcome semantics.",
    ],
    showPermissionMatrix: true,
  },
  integrations: {
    title: "Integration Center",
    eyebrow: "Operations",
    summary: "Connection health, verification, permission, and recovery semantics for provider integrations.",
    stateKeys: ["review", "integrations"],
    sourceSemantics: {
      source: "Phase D integration fixture mapped to provider health records",
      freshness: "Static foundation, not a production read",
      scope: "Organization and Location",
      verification: "Requires provider-specific live checks before status is trusted",
    },
    panels: [
      {
        id: "stripe",
        title: "Stripe",
        status: "Permission Required",
        scope: "Organization",
        source: "Billing provider fixture",
        freshness: "Permission limited",
        verification: "Needs Stripe account and webhook proof",
        consequence: "Checkout, invoice, and subscription changes are blocked until billing access is verified.",
        nextAction: "Request billing permission and run test-mode verification only.",
        fields: [
          ["Connection", "Permission Required"],
          ["Webhook", "Unknown"],
          ["Live claims", "Unavailable"],
        ],
      },
      {
        id: "twilio",
        title: "Twilio",
        status: "Verifying",
        scope: "Location",
        source: "Messaging provider fixture",
        freshness: "Prepared",
        verification: "Needs inbound and outbound event proof",
        consequence: "Lead response and missed-call recovery can stall without verified messaging.",
        nextAction: "Bind provider diagnostics and CommunicationEvent activity.",
        fields: [
          ["SMS", "Verifying"],
          ["Voice", "Unknown"],
          ["Opt-out guard", "Required"],
        ],
      },
      {
        id: "resend",
        title: "Resend",
        status: "Degraded",
        scope: "Organization",
        source: "Email provider fixture",
        freshness: "Stale until DNS proof",
        verification: "Needs sender domain and delivery proof",
        consequence: "Client handoff and support alerts can miss inboxes without email verification.",
        nextAction: "Attach sender diagnostics and branded email proof.",
        fields: [
          ["Sender", "Degraded"],
          ["DNS", "Stale"],
          ["Fallback", "Support escalation"],
        ],
      },
      {
        id: "google-business",
        title: "Google Business Profile",
        status: "Disconnected",
        scope: "Location",
        source: "Local listing fixture",
        freshness: "Unavailable",
        verification: "Needs OAuth and listing ownership proof",
        consequence: "Review and local SEO workflows cannot rely on listing data.",
        nextAction: "Connect only after permission scope is approved.",
        fields: [
          ["Listings", "Disconnected"],
          ["Review feed", "Unavailable"],
          ["Scope", "Location"],
        ],
      },
      {
        id: "analytics",
        title: "Analytics",
        status: "Healthy",
        scope: "Organization",
        source: "Measurement fixture",
        freshness: "Prepared",
        verification: "Needs live DOM and event proof before reporting",
        consequence: "Unverified analytics can create false launch or ROI claims.",
        nextAction: "Keep metrics labelled as not verified until source checks pass.",
        fields: [
          ["Install", "Healthy"],
          ["Events", "Unknown"],
          ["Reporting", "Proof gated"],
        ],
      },
    ],
    safeguards: [
      "Disconnect actions require provider name, affected workflows, and confirmation.",
      "Permission upgrades require role and scope review.",
      "Provider errors must show business consequence and next action.",
    ],
    auditEvents: [
      "integration.connected",
      "integration.permission.requested",
      "integration.health.changed",
    ],
    acceptance: [
      "Connected, Verifying, Healthy, Degraded, Disconnected, Permission Required, and Unknown are represented.",
      "Provider health does not imply live production proof.",
    ],
  },
  billing: {
    title: "Billing",
    eyebrow: "Commerce",
    summary: "Subscription, payment, invoice, scheduled change, and billing permission states.",
    stateKeys: ["review", "billing"],
    sourceSemantics: {
      source: "Phase D billing fixture mapped to Stripe and subscription records",
      freshness: "Static foundation, not a production read",
      scope: "Organization",
      verification: "Requires Stripe account, customer, invoice, and webhook proof",
    },
    panels: [
      {
        id: "subscription",
        title: "Subscription",
        status: "Trial",
        scope: "Organization",
        source: "Subscription fixture",
        freshness: "Prepared",
        verification: "Needs Stripe subscription source",
        consequence: "Wrong subscription state can unlock features or block service incorrectly.",
        nextAction: "Bind status to Stripe and internal entitlement records.",
        fields: [
          ["Plan", "Growth system fixture"],
          ["State", "Trial"],
          ["Live billing", "Unavailable"],
        ],
      },
      {
        id: "payment-method",
        title: "Payment Method",
        status: "Payment Failed",
        scope: "Organization",
        source: "Payment fixture",
        freshness: "Prepared",
        verification: "Needs payment method source and retry events",
        consequence: "Failed payments can interrupt service and support expectations.",
        nextAction: "Route recovery to billing owner without exposing card data.",
        fields: [
          ["Default method", "Restricted"],
          ["Last attempt", "Payment Failed"],
          ["Recovery", "Billing owner"],
        ],
      },
      {
        id: "invoices",
        title: "Invoices",
        status: "Active",
        scope: "Organization",
        source: "Invoice fixture",
        freshness: "Prepared",
        verification: "Needs invoice source and download permission",
        consequence: "Invoice exports must be permissioned and audited.",
        nextAction: "Gate invoice export behind billing permission.",
        fields: [
          ["Invoice list", "Active fixture"],
          ["Export", "Restricted"],
          ["Tax", "Unavailable"],
        ],
      },
      {
        id: "scheduled-change",
        title: "Scheduled Change",
        status: "Scheduled Change",
        scope: "Organization",
        source: "Plan change fixture",
        freshness: "Prepared",
        verification: "Needs pending change source",
        consequence: "Unclear plan changes can surprise clients or misstate entitlements.",
        nextAction: "Attach effective date, requester, approver, and rollback path.",
        fields: [
          ["Effective date", "Pending"],
          ["Requester", "Required"],
          ["Approval", "Owner or Admin"],
        ],
      },
    ],
    safeguards: [
      "Commerce Blue remains reserved for purchase and commercial commitment actions.",
      "Plan cancellation, pause, and downgrade require consequence preview and confirmation.",
      "Payment data never exposes full card or bank details in the browser.",
    ],
    auditEvents: [
      "billing.subscription.changed",
      "billing.payment.failed",
      "billing.invoice.exported",
    ],
    acceptance: [
      "Active, Trial, Past Due, Cancelled, Scheduled Change, and Payment Failed are represented.",
      "Billing states avoid live financial claims until Stripe proof is connected.",
    ],
  },
  usage: {
    title: "Usage",
    eyebrow: "Commerce",
    summary: "Measured, estimated, delayed, unavailable, and out-of-date usage for entitlements.",
    stateKeys: ["review", "usage"],
    sourceSemantics: {
      source: "Phase D usage fixture mapped to future metering records",
      freshness: "Static foundation, not a production read",
      scope: "Organization, Client, Location",
      verification: "Requires metering source and entitlement reconciliation",
    },
    panels: [
      {
        id: "metering",
        title: "Metering",
        status: "Estimated",
        scope: "Organization",
        source: "Usage fixture",
        freshness: "Estimated",
        verification: "Needs measured source",
        consequence: "Estimated usage must not drive overage billing without reconciliation.",
        nextAction: "Separate billable usage from operational activity counts.",
        fields: [
          ["Lead events", "Estimated"],
          ["Message events", "Delayed"],
          ["Voice minutes", "Unavailable"],
        ],
      },
      {
        id: "entitlements",
        title: "Entitlements",
        status: "Current",
        scope: "Client",
        source: "Entitlement fixture",
        freshness: "Prepared",
        verification: "Needs plan and feature source",
        consequence: "Feature access can drift from the purchased plan without reconciliation.",
        nextAction: "Join subscription state to feature gates.",
        fields: [
          ["Automation slots", "Prepared"],
          ["Team seats", "Prepared"],
          ["Export access", "Permission scoped"],
        ],
      },
    ],
    safeguards: [
      "Usage exports require Analyst or higher role.",
      "Delayed usage must show freshness and reconciliation status.",
      "Overage actions are unavailable until measured usage exists.",
    ],
    auditEvents: [
      "usage.exported",
      "usage.reconciled",
      "entitlement.changed",
    ],
    acceptance: [
      "Measured, Estimated, Delayed, Unavailable, and Out Of Date are represented.",
      "Usage values separate measured truth from estimates.",
    ],
  },
  notifications: {
    title: "Notifications",
    eyebrow: "Operations",
    summary: "Alert, digest, escalation, and opt-out preferences with channel scope.",
    stateKeys: ["review", "notifications"],
    sourceSemantics: {
      source: "Phase D notification fixture mapped to future preference records",
      freshness: "Static foundation, not a production read",
      scope: "Organization, Client, Location",
      verification: "Requires preference and consent source binding",
    },
    panels: [
      {
        id: "channels",
        title: "Channels",
        status: "Current",
        scope: "Organization",
        source: "Preference fixture",
        freshness: "Prepared",
        verification: "Needs channel consent source",
        consequence: "Wrong channel preferences can miss urgent incidents or violate consent.",
        nextAction: "Bind email, SMS, and in-app channels to consent-aware preferences.",
        fields: [
          ["Email", "Enabled"],
          ["SMS", "Escalation Only"],
          ["In-app", "Digest"],
        ],
      },
      {
        id: "escalations",
        title: "Escalations",
        status: "Partial",
        scope: "Client",
        source: "Escalation fixture",
        freshness: "Prepared",
        verification: "Needs support workflow source",
        consequence: "Urgent incidents need primary and backup destinations.",
        nextAction: "Attach support priority and owner routing.",
        fields: [
          ["Urgent", "Escalation Only"],
          ["Backup", "Required"],
          ["Quiet hours", "Prepared"],
        ],
      },
    ],
    safeguards: [
      "Opt-out settings must not be bypassed by automation sends.",
      "Security alerts cannot be fully disabled by non-owner roles.",
      "Escalation changes require audit event write.",
    ],
    auditEvents: [
      "notification.preference.changed",
      "notification.alert.sent",
      "notification.escalation.changed",
    ],
    acceptance: [
      "Notification preferences include channel, priority, and escalation semantics.",
      "Consent-sensitive preferences remain scoped and auditable.",
    ],
  },
  security: {
    title: "Security",
    eyebrow: "Risk",
    summary: "Login history, sessions, permission changes, audit events, and security alerts.",
    stateKeys: ["review", "security"],
    sourceSemantics: {
      source: "Phase D security fixture mapped to auth, session, permission, and audit records",
      freshness: "Static foundation, not a production read",
      scope: "Organization, Client, Location",
      verification: "Requires auth provider events and audit source binding",
    },
    panels: [
      {
        id: "login-history",
        title: "Login History",
        status: "Current",
        scope: "Organization",
        source: "Auth event fixture",
        freshness: "Prepared",
        verification: "Needs auth event source",
        consequence: "Suspicious access cannot be investigated without login history.",
        nextAction: "Bind auth provider events with actor, IP, device, source, and outcome.",
        fields: [
          ["Recent sign-ins", "Fixture only"],
          ["New device", "Represented"],
          ["Failed login", "Represented"],
        ],
      },
      {
        id: "sessions",
        title: "Sessions",
        status: "Current",
        scope: "Organization",
        source: "Session fixture",
        freshness: "Prepared",
        verification: "Needs session source and revoke endpoint",
        consequence: "Unmanaged sessions can keep access alive after role or device changes.",
        nextAction: "Wire revoke actions to audited session controls.",
        fields: [
          ["Active sessions", "Fixture only"],
          ["Revoked", "Represented"],
          ["Expiration", "Required"],
        ],
      },
      {
        id: "permissions-changes",
        title: "Permissions Changes",
        status: "Partial",
        scope: "Organization, Client, Location",
        source: "RBAC event fixture",
        freshness: "Prepared",
        verification: "Needs RBAC audit source",
        consequence: "Permission drift can expose billing, exports, or client records.",
        nextAction: "Connect role and scope changes to audit history.",
        fields: [
          ["Actor", "Required"],
          ["Target", "Required"],
          ["Outcome", "Required"],
        ],
      },
      {
        id: "audit-events",
        title: "Audit Events",
        status: "Current",
        scope: "Organization",
        source: "Audit fixture",
        freshness: "Prepared",
        verification: "Needs durable audit source",
        consequence: "Security investigations need immutable action history.",
        nextAction: "Preserve actor, action, target, timestamp, source, and outcome.",
        fields: [
          ["Actor", "Required"],
          ["Timestamp", "Required"],
          ["Source", "Required"],
        ],
      },
      {
        id: "security-alerts",
        title: "Security Alerts",
        status: "Alert",
        scope: "Organization",
        source: "Alert fixture",
        freshness: "Prepared",
        verification: "Needs alert source and resolution lifecycle",
        consequence: "Alerts without routing do not reduce risk.",
        nextAction: "Attach owner, priority, SLA, and resolution state.",
        fields: [
          ["Priority", "Required"],
          ["Owner", "Required"],
          ["Outcome", "Required"],
        ],
      },
    ],
    safeguards: [
      "Session revoke actions show target user, device, and last activity.",
      "Permission changes require role, scope, reason, and approver.",
      "Security alert dismissal requires resolution outcome.",
    ],
    auditEvents: [
      "security.login.recorded",
      "security.session.revoked",
      "security.alert.resolved",
    ],
    acceptance: [
      "Login History, Sessions, Permissions Changes, Audit Events, and Security Alerts are visible.",
      "Security records preserve actor, action, target, timestamp, source, and outcome.",
    ],
  },
  audit: {
    title: "Audit",
    eyebrow: "Risk",
    summary: "Actor, action, target, timestamp, source, and outcome history for enterprise administration.",
    stateKeys: ["review", "security"],
    sourceSemantics: {
      source: "Phase D audit fixture mapped to future immutable audit records",
      freshness: "Static foundation, not a production read",
      scope: "Organization, Client, Location",
      verification: "Requires backend event capture before legal or compliance use",
    },
    panels: [
      {
        id: "audit-history",
        title: "Audit History",
        status: "Current",
        scope: "Organization",
        source: "Audit event fixture",
        freshness: "Prepared",
        verification: "Needs immutable audit source",
        consequence: "Administrative changes cannot be trusted without durable audit history.",
        nextAction: "Write all settings, billing, integration, role, and security events to one audit source.",
        fields: [
          ["Actor", "Required"],
          ["Action", "Required"],
          ["Outcome", "Required"],
        ],
      },
      {
        id: "exports",
        title: "Exports",
        status: "Restricted",
        scope: "Organization",
        source: "Export fixture",
        freshness: "Prepared",
        verification: "Needs export job and permission source",
        consequence: "Untracked exports create data leakage risk.",
        nextAction: "Gate exports by role, scope, and audit event.",
        fields: [
          ["CSV", "Restricted"],
          ["Requester", "Required"],
          ["Retention", "Required"],
        ],
      },
    ],
    safeguards: [
      "Audit event deletion is unavailable.",
      "Exports require role permission and scope confirmation.",
      "Filters must not hide high-risk events by default.",
    ],
    auditEvents: [
      "audit.event.recorded",
      "audit.export.requested",
      "audit.export.completed",
    ],
    acceptance: [
      "Audit records preserve actor, action, target, timestamp, source, and outcome.",
      "Export access is explicitly permission scoped.",
    ],
  },
  support: {
    title: "Support",
    eyebrow: "Operations",
    summary: "Support intake, escalation, SLA, ownership, and recovery paths.",
    stateKeys: ["review", "support"],
    sourceSemantics: {
      source: "Phase D support fixture mapped to future ticket and escalation records",
      freshness: "Static foundation, not a production read",
      scope: "Organization and Client",
      verification: "Requires support message, ticket, and escalation source binding",
    },
    panels: [
      {
        id: "support-center",
        title: "Support Center",
        status: "Open",
        scope: "Client",
        source: "Support fixture",
        freshness: "Prepared",
        verification: "Needs support ticket source",
        consequence: "Support requests need owner, priority, SLA, and client context.",
        nextAction: "Bind support messages to tickets and escalation rules.",
        fields: [
          ["Priority", "Normal fixture"],
          ["Owner", "Required"],
          ["SLA", "Prepared"],
        ],
      },
      {
        id: "escalation",
        title: "Escalation",
        status: "SLA At Risk",
        scope: "Organization",
        source: "Escalation fixture",
        freshness: "Prepared",
        verification: "Needs escalation workflow source",
        consequence: "Urgent issues need durable handoff and accountability.",
        nextAction: "Attach primary owner, backup owner, and alert destinations.",
        fields: [
          ["Urgent route", "Prepared"],
          ["Backup owner", "Required"],
          ["Resolution outcome", "Required"],
        ],
      },
    ],
    safeguards: [
      "Ticket closure requires resolution summary and client-visible outcome.",
      "Urgent escalation owner changes require audit event write.",
      "Support data exports require scoped Export permission.",
    ],
    auditEvents: [
      "support.ticket.created",
      "support.ticket.escalated",
      "support.ticket.resolved",
    ],
    acceptance: [
      "Support and escalation states expose owner, priority, SLA, and next action.",
      "Support data remains scoped by organization and client.",
    ],
  },
};

export const ENTERPRISE_DESTRUCTIVE_ACTION_SAFEGUARDS = [
  "Show affected scope, impacted workflows, and business consequence before confirmation.",
  "Require explicit typed confirmation for delete, disconnect, cancel, and revoke actions.",
  "Capture actor, action, target, timestamp, source, outcome, reason, and approver where required.",
  "Keep recovery or rollback path visible before any destructive action is enabled.",
];

export const ENTERPRISE_ACCESSIBILITY_REQUIREMENTS = [
  "Keyboard reachable navigation, controls, tables, and deep links",
  "Visible focus state through global focus-visible ring",
  "ARIA current section, labelled landmarks, status semantics, and live review fixture notice",
  "Screen reader captions for route map, state contracts, and permission matrix",
  "Reduced motion class coverage for transitions and hover effects",
];

export const ENTERPRISE_RESPONSIVE_VALIDATION = [
  { label: "Desktop", viewport: "1440x900", expectation: "Two-column review surface with persistent section navigation" },
  { label: "Tablet", viewport: "768x900", expectation: "Single-column content with wrapped navigation and no horizontal overflow" },
  { label: "Mobile", viewport: "390x844", expectation: "Stacked cards, full-width controls, readable tables, and safe focus order" },
];

export const ENTERPRISE_REVIEW_ACCEPTANCE = [
  "Routes are protected, noindexed, and excluded from public directory output.",
  "Each system names source, freshness, scope, verification, business consequence, and next action.",
  "Loading, empty, current, partial, stale, delayed, unavailable, restricted, unknown, and recoverable error states are represented.",
  "Billing, usage, and integration states distinguish unavailable or permission-limited data from healthy data.",
  "Commerce Blue remains reserved for purchase and commercial commitment actions.",
  "No production integration, financial state, or live source claim is made by the Phase D foundation.",
];

export const getEnterpriseSection = (sectionId) =>
  ENTERPRISE_SETTINGS_SECTIONS[sectionId] || ENTERPRISE_SETTINGS_SECTIONS.organization;

export const getEnterpriseRoute = (sectionId) =>
  ENTERPRISE_SETTINGS_ROUTES.find((route) => route.id === sectionId) || ENTERPRISE_SETTINGS_ROUTES[0];

export const getStateLabelsForSection = (section) =>
  Array.from(
    new Set(
      (section.stateKeys || ["review"]).flatMap((key) => ENTERPRISE_STATE_CONTRACTS[key] || COMMON_REVIEW_STATES),
    ),
  );
