const INDUSTRY_PUBLIC_PATHS = [
  "/industries",
  "/med-spa",
  "/dental",
  "/chiropractic",
  "/hvac",
  "/plumbing",
  "/roofing",
  "/contractors",
  "/law-firms",
  "/real-estate",
  "/property-services",
  "/auto-services",
  "/cleaning-services",
  "/local-services",
  "/personal-injury",
];

export const PUBLIC_ROUTE_METADATA = {
  "/": {
    key: "home",
    title: "ClientSurge Systems | AI Automation for Local Businesses",
    description: "ClientSurge Systems installs AI automation for local service businesses, including lead capture, missed-call recovery, AI follow-up, appointment booking, review requests, and reactivation workflows.",
  },
  "/pricing": {
    key: "pricing",
    title: "Pricing | Starter, Growth, and Pro AI Automation Packages | ClientSurge Systems",
    description: "Compare ClientSurge Systems packages: Starter System, Growth System, and Pro System with crawlable setup and monthly pricing for AI automation services.",
  },
  "/product-signup": {
    key: "product-signup",
    title: "Complete Your ClientSurge Signup | ClientSurge Systems",
    description: "Choose Starter, Growth, or Pro and continue to secure checkout for your ClientSurge AI automation system.",
  },
  "/signup": {
    key: "signup",
    title: "Complete Your ClientSurge Signup | ClientSurge Systems",
    description: "Start your ClientSurge signup and continue to secure checkout for a Starter, Growth, or Pro AI automation system.",
  },
  "/automations": {
    key: "automations",
    title: "AI Automation Services | ClientSurge Systems",
    description: "Explore ClientSurge automation services for lead response, missed-call text-back, AI follow-up, booking, reviews, and customer reactivation.",
  },
  "/contact": {
    key: "contact",
    title: "Contact ClientSurge Systems | Questions and Demo Requests",
    description: "Contact ClientSurge Systems to ask questions, request a walkthrough, or discuss AI voice agents, lead follow-up, booking automation, and local service business systems.",
  },
  "/privacy": {
    key: "privacy",
    title: "Privacy Policy | ClientSurge Systems",
    description: "Read the ClientSurge Systems privacy policy covering lead forms, SMS communications, AI voice and call automation, analytics, payment processors, data retention, and privacy rights.",
  },
  "/terms": {
    key: "terms",
    title: "Terms of Service | ClientSurge Systems",
    description: "Review the ClientSurge Systems terms of service covering AI automation services, subscriptions, payments, acceptable use, limitations, and customer responsibilities.",
  },
  "/sms-terms": {
    key: "sms-terms",
    title: "SMS Terms and Consent | ClientSurge Systems",
    description: "Read the ClientSurge Systems SMS terms covering opt-in consent, message frequency, message and data rates, STOP opt-out instructions, HELP support, and communication preferences.",
  },
  "/refund-policy": {
    key: "refund-policy",
    title: "Refund and Cancellation Policy | ClientSurge Systems",
    description: "Read the ClientSurge Systems refund and cancellation policy covering setup work, monthly subscriptions, prospective cancellation, and billing support.",
  },
};

export const STATIC_ROUTE_ALIASES = {
  "/privacy-policy": "/privacy",
  "/legal/privacy": "/privacy",
  "/legal/terms": "/terms",
  "/legal/sms": "/sms-terms",
  "/legal/refund": "/refund-policy",
  "/book": "/contact",
  "/book-demo": "/contact",
  "/start": "/contact",
  "/store": "/pricing",
  "/product": "/pricing",
  "/product-landing": "/pricing",
  "/about": "/",
  "/blog": "/",
  "/faq": "/contact",
  "/our-system": "/automations",
  "/testimonials": "/",
  "/proof": "/",
  "/library": "/",
};

export const LEGACY_REDIRECTS = Object.entries(STATIC_ROUTE_ALIASES);

export const PUBLIC_DIRECTORY_PAGES = [
  "/",
  "/pricing",
  "/product-signup",
  "/signup",
  "/automations",
  "/contact",
  "/privacy",
  "/terms",
  "/sms-terms",
  "/refund-policy",
  ...INDUSTRY_PUBLIC_PATHS,
];

export const PUBLIC_ROUTE_PATHS = [...PUBLIC_DIRECTORY_PAGES];
export const APP_SHELL_PUBLIC_PATHS = [...PUBLIC_ROUTE_PATHS];

export const AUTHENTICATED_ROUTE_PREFIXES = [
  "/client",
  "/client-portal",
  "/client-dashboard",
  "/client-saas",
  "/dashboard-entry",
  "/onboarding",
  "/setup",
  "/setup/credentials",
  "/setup/status",
  "/setup/preview",
];

export const ADMIN_ROUTE_PREFIXES = [
  "/admin",
  "/admin-settings",
  "/dashboard",
  "/lead-intelligence",
  "/sam",
  "/medspa-dashboard",
  "/mission-control",
  "/saas/admin",
  "/saas",
];

export const INTERNAL_ROUTE_PREFIXES = [
  "/functions",
  "/function",
  "/internal",
  "/install",
  "/audit",
  "/observability",
  "/reconciliation",
  "/base44",
  "/api",
  "/api/apps",
  "/motion-lab",
  "/admin/AIStatusDashboard",
];

export const NOINDEX_ROUTE_PREFIXES = [
  "/login",
  "/register",
  "/forgot-password",
  "/reset-password",
  "/opt-out",
  "/book",
  "/book-demo",
  "/start",
  "/store",
  "/product",
  "/product-signup",
  "/signup",
  "/success",
  "/order-success",
  "/thank-you",
  "/setup-lookup",
  "/launch-control",
  "/leads/capture",
  ...AUTHENTICATED_ROUTE_PREFIXES,
  ...ADMIN_ROUTE_PREFIXES,
  ...INTERNAL_ROUTE_PREFIXES,
];

export const SITEMAP_STATIC_PATHS = [...PUBLIC_DIRECTORY_PAGES];
export const BLOG_SITEMAP_PATHS = [];

export const ROBOTS_DISALLOW_PATHS = [
  "/admin",
  "/admin/",
  "/dashboard",
  "/dashboard/",
  "/client",
  "/client/",
  "/client-portal",
  "/client-portal/",
  "/client-dashboard",
  "/client-dashboard/",
  "/setup",
  "/setup/",
  "/setup/credentials",
  "/setup/preview",
  "/setup/status",
  "/functions",
  "/functions/",
  "/function",
  "/function/",
  "/internal",
  "/internal/",
  "/onboarding",
  "/onboarding/",
  "/install",
  "/install/",
  "/audit",
  "/audit/",
  "/observability",
  "/observability/",
  "/reconciliation",
  "/reconciliation/",
  "/api/",
  "/base44/",
  "/saas",
  "/saas/",
  "/mission-control",
  "/lead-intelligence",
  "/sam",
  "/medspa-dashboard",
  "/AdminLeadDetail",
  "/AdminSettings",
  "/Dashboard",
  "/ClientPortal",
  "/LeadIntelligence",
  "/Sam",
  "/MedSpaDashboard",
  "/WebsiteSpecPreview",
  "/NotFound",
];
