const RUN_PREFIX = 'qa-lead-proof';

export const QA_LEAD_PROOF_CONFIRM_PHRASE = 'GENERATE QA LEAD PROOF';

export function buildQaLeadProofRunId(now = new Date()) {
  return `${RUN_PREFIX}-${now.toISOString().replace(/[:.]/g, '-')}`;
}

export function buildQaLeadProofFixtures({ runId = buildQaLeadProofRunId(), now = new Date().toISOString() } = {}) {
  const shared = {
    run_id: runId,
    generated_at: now,
    source: 'qa_lead_proof_generator',
    consent_source: 'qa_lead_proof_generator',
    source_page: 'admin_qa_tools',
    automation_enabled: false,
    cadence_paused: true,
    cadence_paused_at: now,
  };

  return [
    {
      key: 'website_internal_marker',
      entity: 'WebsiteLead',
      expected_bucket: 'hidden_archived_ignored',
      expected_reason: 'internal/test source marker should stay hidden and never trigger outbound automation',
      data: {
        ...shared,
        business_name: `Install Test — ClientSurge Proof ${runId}`,
        full_name: 'ClientSurge QA Proof',
        first_name: 'QA',
        email: `test+${runId}@clientsurge-install.internal`,
        phone_number: '+16025550100',
        business_type: 'test',
        service_interest: 'QA proof only',
        message: 'Generated by QA Lead Proof Generator. Do not contact.',
        lead_status: 'ignored',
        reply_status: 'none',
        booking_status: 'none',
        archived: true,
        archived_at: now,
        quality_notes: `qa_lead_proof:${runId}:internal_marker`,
      },
    },
    {
      key: 'lead_quarantine_marker',
      entity: 'Leads',
      expected_bucket: 'quarantine_candidate',
      expected_reason: 'internal/test marker should be hidden from trusted lead views',
      data: {
        business_name: `ClientSurge Smoke QA ${runId}`,
        full_name: 'ClientSurge QA Proof',
        email: `qa+${runId}@clientsurge.test`,
        phone: '+16025550101',
        website: 'https://clientsurge.test',
        business_type: 'test',
        city: 'Phoenix',
        state: 'AZ',
        source: 'qa_lead_proof_generator',
        quality_review_status: 'quarantine_candidate',
        quality_reason: `QA lead proof generator internal/test marker ${runId}`,
        quality_reason_codes: ['internal_test', 'example_email', 'test_phone_555', 'test_website', 'qa_lead_proof_generator'],
        quality_confidence: 99,
        audited_at: now,
        lead_state: 'NEW',
        status: 'New',
      },
    },
    {
      key: 'lead_duplicate_marker_a',
      entity: 'Leads',
      expected_bucket: 'duplicate_candidate',
      expected_reason: 'shared duplicate key should appear in Duplicate Keeper Review',
      data: {
        business_name: `QA Duplicate Dental ${runId}`,
        full_name: 'QA Duplicate One',
        email: `qa-duplicate-a+${runId}@clientsurge.test`,
        phone: '+16025550102',
        website: 'https://qa-duplicate.clientsurge.test',
        business_type: 'Dental',
        city: 'Phoenix',
        state: 'AZ',
        source: 'qa_lead_proof_generator',
        dedupe_status: 'duplicate_candidate',
        dedupe_group_key: `qa-proof-duplicate:${runId}`,
        quality_review_status: 'duplicate_candidate',
        quality_reason: `QA duplicate proof group: ${runId}`,
        quality_reason_codes: ['duplicate_candidate', 'qa_lead_proof_generator'],
        quality_confidence: 95,
        audited_at: now,
      },
    },
    {
      key: 'lead_duplicate_marker_b',
      entity: 'Leads',
      expected_bucket: 'duplicate_candidate',
      expected_reason: 'second member proves duplicate group rendering without automatic merge/delete',
      data: {
        business_name: `QA Duplicate Dental ${runId}`,
        full_name: 'QA Duplicate Two',
        email: `qa-duplicate-b+${runId}@clientsurge.test`,
        phone: '+16025550102',
        website: 'https://qa-duplicate.clientsurge.test',
        business_type: 'Dental',
        city: 'Phoenix',
        state: 'AZ',
        source: 'qa_lead_proof_generator',
        dedupe_status: 'duplicate_candidate',
        dedupe_group_key: `qa-proof-duplicate:${runId}`,
        quality_review_status: 'duplicate_candidate',
        quality_reason: `QA duplicate proof group: ${runId}`,
        quality_reason_codes: ['duplicate_candidate', 'qa_lead_proof_generator'],
        quality_confidence: 95,
        audited_at: now,
      },
    },
    {
      key: 'lead_no_contact_marker',
      entity: 'Leads',
      expected_bucket: 'blocked_missing_contact',
      expected_reason: 'missing email/phone/website should be blocked from outreach readiness',
      data: {
        business_name: `QA Raw Import No Contact ${runId}`,
        full_name: 'QA No Contact',
        business_type: 'Unknown',
        city: '',
        state: '',
        source: 'qa_lead_proof_generator',
        quality_review_status: 'quarantine_candidate',
        quality_reason: `QA raw import no contact proof ${runId}`,
        quality_reason_codes: ['raw_import_no_contact', 'missing_city_state_no_contact', 'qa_lead_proof_generator'],
        quality_confidence: 98,
        audited_at: now,
      },
    },
  ];
}

export function summarizeQaLeadProofFixtures(fixtures = []) {
  return fixtures.reduce((acc, fixture) => {
    acc.total += 1;
    acc.by_entity[fixture.entity] = (acc.by_entity[fixture.entity] || 0) + 1;
    acc.expected_buckets[fixture.expected_bucket] = (acc.expected_buckets[fixture.expected_bucket] || 0) + 1;
    return acc;
  }, { total: 0, by_entity: {}, expected_buckets: {} });
}
