// Master system diagram data — defines the full lead journey and all 6 service nodes
// Positions are percent-based (x, y) relative to the canvas container.
// Layout: lead_in (top center) → ai_qualify (upper center) → 6 services (fan across middle) → outcomes (bottom)

export const DIAGRAM_NODES = [
  {
    id: "lead_in",
    label: "New Lead Arrives",
    icon: "📥",
    type: "trigger",
    description: "A lead comes in via web form, missed call, Facebook Ad, or referral. The journey begins.",
    stat: "24/7 capture",
    color: "#00AEEF",
    order: 0,
    x: 50,
    y: 8,
  },
  {
    id: "ai_qualify",
    label: "AI Scores & Routes",
    icon: "🧠",
    type: "system",
    description: "AI instantly scores the lead 0–100, classifies intent, and routes to the right automation track.",
    stat: "<2 sec routing",
    color: "#6366f1",
    order: 1,
    x: 50,
    y: 28,
  },
  // 6 service nodes — evenly fanned across x: 8% to 92%, fixed at y: 58%
  {
    id: "instant_lead_response",
    label: "Instant Lead Response",
    icon: "⚡",
    type: "service",
    serviceKey: "instant_lead_response",
    slug: "instant-lead-response",
    description: "A personalized SMS fires to the lead within 4 seconds of submission — before any competitor can respond.",
    stat: "<4 sec SMS",
    color: "#00AEEF",
    order: 2,
    x: 8,
    y: 58,
  },
  {
    id: "missed_call_text_back",
    label: "Missed Call Text-Back",
    icon: "📞",
    type: "service",
    serviceKey: "missed_call_text_back",
    slug: "missed-call-text-back",
    description: "Every missed call triggers an automatic text-back within 60 seconds, recovering leads you'd otherwise lose.",
    stat: "60 sec recovery",
    color: "#f59e0b",
    order: 3,
    x: 24,
    y: 58,
  },
  {
    id: "nurture_sequence",
    label: "14-Day Nurture",
    icon: "🔄",
    type: "service",
    serviceKey: "nurture_sequence_14d",
    slug: "nurture-sequence",
    description: "An 8-step SMS + email sequence runs over 14 days to keep leads warm until they're ready to book.",
    stat: "8 touchpoints",
    color: "#10b981",
    order: 4,
    x: 40,
    y: 58,
  },
  {
    id: "ai_booking_agent",
    label: "AI Booking Agent",
    icon: "📅",
    type: "service",
    serviceKey: "ai_booking_agent",
    slug: "ai-booking-agent",
    description: "Guides warm leads through a structured booking flow with intake, confirmation, and reminders — fully automated.",
    stat: "Auto-confirmed",
    color: "#8b5cf6",
    order: 5,
    x: 56,
    y: 58,
  },
  {
    id: "lead_reactivation",
    label: "Lead Reactivation",
    icon: "💰",
    type: "service",
    serviceKey: "lead_reactivation",
    slug: "lead-reactivation",
    description: "Dormant leads from your database get re-engaged with targeted batch messaging to revive lost revenue.",
    stat: "Batch re-engage",
    color: "#ef4444",
    order: 6,
    x: 72,
    y: 58,
  },
  {
    id: "review_request",
    label: "Review Request",
    icon: "⭐",
    type: "service",
    serviceKey: "review_request",
    slug: "review-request",
    description: "After each completed appointment, an automated review request fires to build your reputation on autopilot.",
    stat: "Post-visit auto",
    color: "#f97316",
    order: 7,
    x: 88,
    y: 58,
  },
  // Outcomes
  {
    id: "lead_booked",
    label: "Lead Booked",
    icon: "✅",
    type: "outcome",
    description: "The lead is converted into a confirmed, paid appointment. The system logs revenue and resets for the next lead.",
    stat: "Revenue captured",
    color: "#22c55e",
    order: 8,
    x: 38,
    y: 85,
  },
  {
    id: "reputation_growth",
    label: "Reputation Grows",
    icon: "🏆",
    type: "outcome",
    description: "5-star reviews accumulate passively, driving organic discovery and trust for future leads.",
    stat: "Compounding ROI",
    color: "#eab308",
    order: 9,
    x: 74,
    y: 85,
  },
];

export const DIAGRAM_CONNECTIONS = [
  { from: "lead_in", to: "ai_qualify" },
  { from: "ai_qualify", to: "instant_lead_response" },
  { from: "ai_qualify", to: "missed_call_text_back" },
  { from: "ai_qualify", to: "nurture_sequence" },
  { from: "ai_qualify", to: "ai_booking_agent" },
  { from: "ai_qualify", to: "lead_reactivation" },
  { from: "ai_qualify", to: "review_request" },
  { from: "instant_lead_response", to: "lead_booked" },
  { from: "missed_call_text_back", to: "lead_booked" },
  { from: "nurture_sequence", to: "lead_booked" },
  { from: "ai_booking_agent", to: "lead_booked" },
  { from: "lead_reactivation", to: "lead_booked" },
  { from: "review_request", to: "reputation_growth" },
];

export const SERVICE_NODES = DIAGRAM_NODES.filter((n) => n.type === "service");