name = "clientsurge-security-edge"
main = "cloudflare/clientsurge-security-telegram-wrapper.mjs"
compatibility_date = "2026-04-23"
workers_dev = false

[[routes]]
pattern = "clientsurgesystems.com/*"
zone_name = "clientsurgesystems.com"

[[routes]]
pattern = "www.clientsurgesystems.com/*"
zone_name = "clientsurgesystems.com"

[[d1_databases]]
binding = "ANALYTICS_DB"
database_name = "clientsurge-visitor-analytics"
database_id = "9d0df58b-e737-4289-94d8-24c4a10747be"
migrations_dir = "migrations"

[triggers]
crons = ["* * * * *"]
