import { secureJson } from "../_shared/response.ts";
/**
 * runIntegrationHealthCheck
 * Scheduled function that:
 * 1. Live-pings Twilio, Resend, and Stripe APIs
 * 2. Checks for persistent failure patterns in CommunicationEvents
 * 3. Auto-creates ProjectTask fix-it tickets for admins when issues persist
 * 4. Deduplicates tasks so the same issue doesn't spawn duplicate tickets
 */
import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';
import { resendFetch } from "../_shared/resendFetch.js";
import { stripeFetch, twilioFetch } from "../_shared/providerFetch.js";

// Thresholds for auto-task creation
const FAILURE_THRESHOLD = 3;       // failures in window
const FAILURE_WINDOW_HOURS = 6;    // hours to look back
const TASK_DEDUP_HOURS = 24;       // don't create same task twice within this window

async function pingTwilio() {
  const sid = Deno.env.get('TWILIO_ACCOUNT_SID');
  const token = Deno.env.get('TWILIO_AUTH_TOKEN');
  if (!sid || !token) return { ok: false, error: 'Credentials not set (TWILIO_ACCOUNT_SID / TWILIO_AUTH_TOKEN)' };
  try {
    const res = await twilioFetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}.json`, {
      headers: { 'Authorization': 'Basic ' + btoa(`${sid}:${token}`) },
    });
    if (res.ok) return { ok: true };
    const body = await res.json().catch(() => ({}));
    return { ok: false, error: body.message || `HTTP ${res.status}` };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

async function pingResend() {
  const key = Deno.env.get('RESEND_API_KEY');
  if (!key) return { ok: false, error: 'RESEND_API_KEY not set' };
  try {
    const res = await resendFetch('https://api.resend.com/domains', {
      headers: { 'Authorization': `Bearer ${key}` },
    });
    if (res.ok) return { ok: true };
    const body = await res.json().catch(() => ({}));
    return { ok: false, error: body.message || body.name || `HTTP ${res.status}` };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

async function pingStripe() {
  const key = Deno.env.get('STRIPE_SECRET_KEY') || Deno.env.get('STRIPE_LIVE_SECRET_KEY');
  if (!key) return { ok: false, error: 'STRIPE_SECRET_KEY not set' };
  try {
    const res = await stripeFetch('https://api.stripe.com/v1/balance', {
      headers: { 'Authorization': `Bearer ${key}` },
    });
    if (res.ok) return { ok: true };
    const body = await res.json().catch(() => ({}));
    return { ok: false, error: body.error?.message || `HTTP ${res.status}` };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

async function ensureFixItTask(base44, { provider, errorSummary, severity }) {
  const taskTitle = `[Integration Alert] ${provider} connection issue detected`;
  const now = Date.now();
  const dedupCutoff = new Date(now - TASK_DEDUP_HOURS * 60 * 60 * 1000).toISOString();

  // Check for existing open task for this provider created recently
  const existing = await base44.asServiceRole.entities.ProjectTask.list('-created_date', 50);
  const duplicate = (existing || []).find(t =>
    t.title === taskTitle &&
    t.status !== 'done' &&
    t.created_date > dedupCutoff
  );

  if (duplicate) {
    console.log(`[healthCheck] Dedup — task already exists for ${provider}: ${duplicate.id}`);
    return { created: false, task_id: duplicate.id };
  }

  const task = await base44.asServiceRole.entities.ProjectTask.create({
    title: taskTitle,
    domain: 'D09_DevOps_Monitoring',
    status: 'pending',
    priority: severity === 'critical' ? 'critical' : 'high',
    assigned_agent: 'Any',
    notes: `Auto-generated by Integration Health Check (${new Date().toISOString()})\n\nProvider: ${provider}\nError: ${errorSummary}\n\nSteps to resolve:\n1. Go to Admin → Integration Health\n2. Check provider credentials in secrets dashboard\n3. Review recent CommunicationEvent failures\n4. Test connection using the "Test Connection" button\n5. Mark this task done once resolved.`,
    thread: 'integration_health',
  });

  console.log(`[healthCheck] Created fix-it task for ${provider}: ${task.id}`);
  return { created: true, task_id: task.id };
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    // Allow scheduled (no auth) or admin-triggered
    let isScheduled = false;
    try {
      const user = await base44.auth.me();
      if (user && user.role !== 'admin') {
        return secureJson({ error: 'Admin access required' }, { status: 403 });
      }
    } catch {
      // Unauthenticated = scheduled trigger, allow it
      isScheduled = true;
    }

    const now = Date.now();
    const windowCutoff = new Date(now - FAILURE_WINDOW_HOURS * 60 * 60 * 1000).toISOString();
    const results = {};
    const tasksCreated = [];

    // 1. Live API pings (parallel)
    const [twilioResult, resendResult, stripeResult] = await Promise.all([
      pingTwilio(),
      pingResend(),
      pingStripe(),
    ]);

    results.twilio = { ...twilioResult, provider: 'Twilio SMS' };
    results.resend = { ...resendResult, provider: 'Resend Email' };
    results.stripe = { ...stripeResult, provider: 'Stripe Payments' };

    // 2. Check CommunicationEvent failure patterns
    const recentFailures = await base44.asServiceRole.entities.CommunicationEvent.filter(
      { status: 'failed' }, '-created_date', 200
    );
    const windowedFailures = (recentFailures || []).filter(
      e => e.created_date > windowCutoff
    );

    const failuresByProvider = {};
    for (const evt of windowedFailures) {
      const p = evt.provider || 'unknown';
      if (!failuresByProvider[p]) failuresByProvider[p] = [];
      failuresByProvider[p].push(evt);
    }

    // 3. Auto-create fix-it tasks for persistent failures
    const checks = [
      { key: 'twilio', result: twilioResult, displayName: 'Twilio SMS' },
      { key: 'resend', result: resendResult, displayName: 'Resend Email' },
      { key: 'stripe', result: stripeResult, displayName: 'Stripe Payments' },
    ];

    for (const { key, result, displayName } of checks) {
      const eventFailures = failuresByProvider[key] || [];
      const hasLivePingFailure = !result.ok;
      const hasPersistentEventFailures = eventFailures.length >= FAILURE_THRESHOLD;

      if (hasLivePingFailure || hasPersistentEventFailures) {
        const severity = (hasLivePingFailure && hasPersistentEventFailures) ? 'critical' : 'warning';
        const errorParts = [];
        if (hasLivePingFailure) errorParts.push(`Live ping failed: ${result.error}`);
        if (hasPersistentEventFailures) errorParts.push(`${eventFailures.length} CommunicationEvent failures in last ${FAILURE_WINDOW_HOURS}h`);

        const taskResult = await ensureFixItTask(base44, {
          provider: displayName,
          errorSummary: errorParts.join(' | '),
          severity,
        });
        tasksCreated.push({ provider: displayName, ...taskResult });
      }
    }

    // 4. Log the health check run as a CommunicationEvent
    const allHealthy = checks.every(c => c.result.ok);
    await base44.asServiceRole.entities.CommunicationEvent.create({
      channel: 'internal',
      direction: 'system',
      event_type: 'status_update',
      provider: 'internal',
      status: allHealthy ? 'processed' : 'failed',
      subject: `Integration Health Check — ${allHealthy ? 'All OK' : 'Issues Detected'}`,
      message_body: JSON.stringify({
        twilio: results.twilio.ok,
        resend: results.resend.ok,
        stripe: results.stripe.ok,
        tasks_created: tasksCreated.filter(t => t.created).length,
      }),
      metadata_json: JSON.stringify({ triggered_by: isScheduled ? 'scheduler' : 'admin', failure_counts: Object.fromEntries(Object.entries(failuresByProvider).map(([k, v]) => [k, v.length])) }),
    });

    return secureJson({
      success: true,
      generated_at: new Date().toISOString(),
      ping_results: results,
      failure_counts: Object.fromEntries(Object.entries(failuresByProvider).map(([k, v]) => [k, v.length])),
      tasks: tasksCreated,
      all_healthy: allHealthy,
    });

  } catch (error) {
    console.error('[runIntegrationHealthCheck] Error:', error);
    return secureJson({ error: error.message }, { status: 500 });
  }
});