export const PHASE_B_REQUIRED_STATES = [
  "loading",
  "empty",
  "unknown",
  "permission",
  "unavailable",
  "partial",
  "stale",
  "delayed",
  "current",
];

const fixtureScope = "Static Phase B review fixture";
const fixtureTimestamp = "2026-07-19T04:00:00-07:00";

export const sharedFixtureDisclosure = {
  source: "Static review fixture",
  verification: "reported",
  freshness: "current",
  timestamp: fixtureTimestamp,
  scope: fixtureScope,
  explanation: "This isolated fixture exists for rendered review. It is not connected to production data.",
};

export const briefActions = [
  {
    id: "brief-action-follow-up",
    title: "Review verified follow-up queue",
    reason: "Connected activity shows customer follow-up work is waiting, but no revenue impact is inferred.",
    evidence: [
      { id: "brief-evidence-source", label: "Lead activity source is connected for the selected period." },
      { id: "brief-evidence-age", label: "Follow-up age is visible before any urgency label is applied." },
    ],
    priority: "high",
    owner: "customer",
    confidence: "high",
    verification: "verified",
    freshness: "current",
    source: "CRM activity source",
    actionLabel: "Open follow-up queue",
    actionHref: "#brief-follow-up",
  },
];

export const morningBriefFixtures = {
  loading: {
    state: "loading",
    period: "Today so far",
    summary: "Checking connected sources before preparing the brief.",
  },
  empty: {
    state: "empty",
    period: "Today so far",
    summary: "No verified activity occurred during this period.",
    disclosure: {
      ...sharedFixtureDisclosure,
      verification: "verified",
      explanation: "The selected period is valid and all required connected sources reported no activity.",
    },
  },
  unknown: {
    state: "unknown",
    period: "Today so far",
    summary: "The brief cannot classify activity because evidence is insufficient.",
  },
  permission: {
    state: "permission",
    period: "Today so far",
    summary: "Your current role cannot view one or more brief sources.",
  },
  unavailable: {
    state: "unavailable",
    period: "Today so far",
    summary: "The brief source could not be reached.",
  },
  partial: {
    state: "partial",
    period: "Today so far",
    summary: "Priority actions are shown from available sources; missing sources are disclosed.",
    coverage: "Calls and leads are current. Reviews and revenue are not connected for this fixture.",
    missing: ["Reviews", "Collected revenue"],
    actions: briefActions,
  },
  stale: {
    state: "stale",
    period: "Yesterday",
    summary: "The brief is viewable, but the newest source update is outside its expected freshness window.",
    actions: briefActions,
  },
  delayed: {
    state: "delayed",
    period: "This week",
    summary: "One source has confirmed processing delay. Current items remain separated from delayed ones.",
    actions: briefActions,
  },
  current: {
    state: "current",
    period: "Today so far",
    summary: "Priority actions and verified outcomes are current for connected sources.",
    actions: briefActions,
    highlights: [
      {
        id: "brief-highlight-calls",
        title: "Calls",
        value: "Verified activity available",
        description: "Call outcomes are visible only when the connected phone source reports them.",
        source: "Phone activity source",
        verification: "verified",
        freshness: "current",
        confidence: "high",
        deepLink: { label: "Open calls", href: "#brief-calls" },
      },
      {
        id: "brief-highlight-booking",
        title: "Booking",
        value: "No verified booking issue",
        description: "No booking-path failure is displayed without supporting journey evidence.",
        source: "Booking source",
        verification: "verified",
        freshness: "current",
        confidence: "medium",
        deepLink: { label: "Open booking", href: "#brief-booking" },
      },
    ],
  },
};

export const healthDomains = [
  {
    id: "health-domain-website",
    name: "Website",
    status: "unknown",
    statusLabel: "Unknown",
    reason: "The latest critical-journey evidence is missing, so this domain is not treated as healthy.",
    evidence: [
      { id: "health-website-journey", label: "Critical journey source must be current before classification." },
    ],
    recommendation: "Verify website journey evidence",
    confidence: "insufficient",
    verification: "unknown",
    freshness: "unknown",
    source: "Website journey source",
    nextAction: "Verify journey evidence",
  },
  {
    id: "health-domain-lead-capture",
    name: "Lead Capture",
    status: "action_required",
    statusLabel: "Action required",
    reason: "A resolution path is available for a verified customer journey issue.",
    evidence: [
      { id: "health-lead-source", label: "Lead routing source is connected for the review fixture." },
      { id: "health-lead-path", label: "A specific routing review destination is available." },
    ],
    recommendation: "Open the lead routing review and confirm the affected path.",
    confidence: "high",
    verification: "verified",
    freshness: "current",
    source: "Lead routing source",
    nextAction: "Open routing review",
  },
  {
    id: "health-domain-ai-workforce",
    name: "AI Workforce",
    status: "degraded",
    statusLabel: "Degraded",
    reason: "Automation coverage is visible, but the fixture marks one handoff as incomplete.",
    evidence: [
      { id: "health-ai-handoff", label: "AI-to-human handoff context must remain auditable." },
    ],
    recommendation: "Review incomplete handoffs before treating automation as healthy.",
    confidence: "medium",
    verification: "reported",
    freshness: "current",
    source: "AI workforce fixture",
    nextAction: "Review handoffs",
  },
  {
    id: "health-domain-communication",
    name: "Communication",
    status: "attention_needed",
    statusLabel: "Attention needed",
    reason: "Communication status can continue, but source coverage requires review.",
    evidence: [
      { id: "health-communication-source", label: "Message-source coverage is partial in the fixture." },
    ],
    recommendation: "Confirm communication source coverage before escalating status.",
    confidence: "medium",
    verification: "reported",
    freshness: "current",
    source: "Communication fixture",
    nextAction: "Review communication coverage",
  },
  {
    id: "health-domain-bookings",
    name: "Bookings",
    status: "blocked",
    statusLabel: "Blocked",
    reason: "Booking classification cannot proceed while confirmation evidence is missing.",
    evidence: [
      { id: "health-booking-confirmation", label: "Confirmation-source evidence is absent from this fixture." },
    ],
    recommendation: "Connect or verify the booking confirmation source.",
    confidence: "insufficient",
    verification: "unknown",
    freshness: "not_connected",
    source: "Booking confirmation source",
    nextAction: "Open booking setup",
  },
  {
    id: "health-domain-reviews",
    name: "Reviews",
    status: "unavailable",
    statusLabel: "Unavailable",
    reason: "The review source cannot currently be queried.",
    evidence: [
      { id: "health-review-source", label: "Review source response is unavailable in this fixture." },
    ],
    recommendation: "Retry the review source before classifying reputation health.",
    confidence: "insufficient",
    verification: "unknown",
    freshness: "unavailable",
    source: "Review source",
    nextAction: "Retry review source",
  },
  {
    id: "health-domain-integrations",
    name: "Integrations",
    status: "healthy",
    statusLabel: "Healthy",
    reason: "The fixture shows integration inventory can be classified only with current evidence.",
    evidence: [
      { id: "health-integrations-inventory", label: "Integration inventory evidence is current for this fixture." },
    ],
    recommendation: "Keep monitoring integration freshness; do not infer downstream outcomes.",
    confidence: "high",
    verification: "verified",
    freshness: "current",
    source: "Integration inventory source",
    nextAction: "Open integrations",
  },
  {
    id: "health-domain-revenue-visibility",
    name: "Revenue Visibility",
    status: "unknown",
    statusLabel: "Unknown",
    reason: "Revenue visibility cannot be classified without approved finance-source access.",
    evidence: [
      { id: "health-revenue-permission", label: "Finance source visibility is not proven in this fixture." },
    ],
    recommendation: "Request finance-source permission before showing revenue health.",
    confidence: "insufficient",
    verification: "unknown",
    freshness: "permission_restricted",
    source: "Revenue visibility source",
    nextAction: "Request finance permission",
  },
];

export const businessHealthFixtures = {
  loading: { state: "loading", headline: "Checking health contributors." },
  empty: {
    state: "empty",
    headline: "No assessable health domains are configured yet.",
    description: "Connect at least one eligible source before a health assessment is shown.",
  },
  unknown: {
    state: "unknown",
    headline: "Overall health unknown",
    description: "Unknown is not treated as healthy. More evidence is required.",
  },
  permission: { state: "permission", headline: "Health details require additional permission." },
  unavailable: { state: "unavailable", headline: "Health sources are unavailable." },
  partial: {
    state: "partial",
    headline: "Partial health assessment",
    description: "Only eligible domains with current evidence are classified.",
    coverage: "Lead capture is current. Website journey evidence is unknown.",
    domains: healthDomains,
  },
  stale: {
    state: "stale",
    headline: "Health evidence is stale",
    description: "The last assessment is visible but cannot be promoted to current.",
    domains: healthDomains,
  },
  delayed: {
    state: "delayed",
    headline: "Health evidence delayed",
    description: "One contributor is delayed by its source, so confidence is reduced.",
    domains: healthDomains,
  },
  current: {
    state: "current",
    headline: "Qualitative health assessment",
    description: "No numeric score is shown because no approved weighting contract exists.",
    domains: healthDomains,
  },
};

export const opportunityItems = [
  {
    id: "opportunity-lead-follow-up",
    title: "Review aging lead follow-up",
    explanation: "A verified lead workflow has items that require human review.",
    category: "customer follow-up",
    priority: "high",
    owner: "customer",
    confidence: "high",
    verification: "verified",
    freshness: "current",
    source: "Lead activity source",
    impact: "Customer experience",
    lifecycle: "Detected",
    status: "Detected",
    evidence: [
      { id: "opp-evidence-rule", label: "Detection rule is available and versioned for review." },
      { id: "opp-evidence-source", label: "Source activity is current for the selected period." },
    ],
    actionLabel: "Review lead queue",
  },
  {
    id: "opportunity-source-coverage",
    title: "Reconnect review source",
    explanation: "Review intelligence is not connected, so reputation opportunities are not classified.",
    category: "data coverage",
    priority: "medium",
    owner: "clientsurge_staff",
    confidence: "insufficient",
    verification: "unknown",
    freshness: "not_connected",
    source: "Review source",
    impact: "Data coverage",
    lifecycle: "Assigned",
    status: "Assigned",
    evidence: [
      { id: "opp-evidence-missing", label: "Review source is absent from the coverage matrix." },
    ],
    actionLabel: "Open source setup",
  },
];

export const opportunityLifecycleStates = [
  "Detected",
  "Reviewed",
  "Assigned",
  "Working",
  "Completed",
  "Dismissed",
  "Expired",
];

export const opportunityFixtures = {
  loading: { state: "loading", headline: "Checking opportunity detectors." },
  empty: {
    state: "empty",
    headline: "No current opportunities meet the selected criteria.",
    description: "This does not mean the business is fully optimized.",
  },
  unknown: { state: "unknown", headline: "Opportunity status unknown." },
  permission: { state: "permission", headline: "Opportunity details require additional permission." },
  unavailable: { state: "unavailable", headline: "Opportunity detectors are unavailable." },
  partial: {
    state: "partial",
    headline: "Partial opportunity coverage",
    coverage: "Lead follow-up detector is current. Reputation detector is not connected.",
    opportunities: opportunityItems,
  },
  stale: {
    state: "stale",
    headline: "Opportunity evidence is stale",
    opportunities: opportunityItems,
  },
  delayed: {
    state: "delayed",
    headline: "Opportunity processing delayed",
    opportunities: opportunityItems,
  },
  current: {
    state: "current",
    headline: "Prioritized opportunities",
    opportunities: opportunityItems,
  },
};

export const revenueClasses = [
  {
    id: "collected-revenue",
    label: "Collected Revenue",
    value: "Verified source amount",
    description: "Collected revenue is displayed separately from invoiced, projected, and estimated values.",
    verification: "verified",
    freshness: "current",
    confidence: "high",
    source: "Canonical payment source",
  },
  {
    id: "invoiced-revenue",
    label: "Invoiced Revenue",
    value: "Class boundary only",
    description: "Invoiced revenue is not treated as collected revenue without payment-source proof.",
    verification: "reported",
    freshness: "current",
    confidence: "medium",
    source: "Invoice source fixture",
  },
  {
    id: "pipeline-revenue",
    label: "Pipeline Revenue",
    value: "Pipeline only",
    description: "Pipeline revenue remains a separate opportunity-stage class.",
    verification: "reported",
    freshness: "current",
    confidence: "medium",
    source: "Pipeline source fixture",
  },
  {
    id: "attributed-revenue",
    label: "Attributed Revenue",
    value: "Attribution deferred",
    description: "Attributed revenue is not shown as verified until an approved attribution method exists.",
    verification: "unknown",
    freshness: "unknown",
    confidence: "insufficient",
    source: "Attribution source fixture",
  },
  {
    id: "projected-revenue",
    label: "Projected Revenue",
    value: "Projection only",
    description: "Projected revenue is separated from collected, invoiced, and estimated classes.",
    verification: "estimated",
    freshness: "current",
    confidence: "low",
    source: "Projection assumptions fixture",
  },
  {
    id: "estimated-revenue",
    label: "Estimated Revenue",
    value: "Estimated only",
    description: "Estimated revenue is never merged into verified collected totals.",
    verification: "estimated",
    freshness: "current",
    confidence: "low",
    source: "Reported assumptions",
  },
  {
    id: "outstanding-revenue",
    label: "Outstanding Revenue",
    value: "Outstanding only",
    description: "Outstanding revenue requires its own collection and aging evidence.",
    verification: "reported",
    freshness: "delayed",
    confidence: "medium",
    source: "Accounts receivable fixture",
  },
  {
    id: "unknown-revenue",
    label: "Unknown",
    value: "Not shown as zero",
    description: "Unknown revenue does not become a zero-value result.",
    verification: "unknown",
    freshness: "unknown",
    confidence: "insufficient",
    source: "Missing source",
  },
];

export const revenueFixtures = {
  loading: { state: "loading", headline: "Checking revenue sources." },
  empty: {
    state: "empty",
    headline: "No verified revenue is available for this period.",
    description: "A true zero appears only when zero is verified by the canonical source.",
  },
  unknown: { state: "unknown", headline: "Revenue status unknown." },
  permission: { state: "permission", headline: "Revenue details require finance permission." },
  unavailable: { state: "unavailable", headline: "Revenue source unavailable." },
  partial: {
    state: "partial",
    headline: "Partial revenue coverage",
    coverage: "Collected source is current. Attribution and estimates are separated.",
    classes: revenueClasses,
  },
  stale: {
    state: "stale",
    headline: "Revenue data is stale",
    classes: revenueClasses,
  },
  delayed: {
    state: "delayed",
    headline: "Revenue reconciliation delayed",
    classes: revenueClasses,
  },
  current: {
    state: "current",
    headline: "Revenue classes separated",
    classes: revenueClasses,
  },
};

export const websiteSignals = [
  {
    id: "website-speed",
    group: "technical",
    label: "Speed",
    status: "Current",
    recommendation: "Keep monitoring source freshness.",
    evidence: "Speed evidence is represented as a class only; no performance score is invented.",
    verification: "verified",
    freshness: "current",
    confidence: "high",
    source: "Website technical fixture",
  },
  {
    id: "website-availability",
    group: "technical",
    label: "Availability",
    status: "Current",
    recommendation: "Keep availability separate from conversion claims.",
    evidence: "Availability source is current for this static fixture.",
    verification: "verified",
    freshness: "current",
    confidence: "high",
    source: "Website technical fixture",
  },
  {
    id: "website-errors",
    group: "technical",
    label: "Errors",
    status: "Unknown",
    recommendation: "Connect error monitoring before classifying route health.",
    evidence: "Error-source evidence is missing in this fixture.",
    verification: "unknown",
    freshness: "unknown",
    confidence: "insufficient",
    source: "Error monitoring fixture",
  },
  {
    id: "website-forms",
    group: "technical",
    label: "Forms",
    status: "Action required",
    recommendation: "Open the lead form verification path.",
    evidence: "The fixture demonstrates an action-required conversion step without claiming revenue loss.",
    verification: "verified",
    freshness: "current",
    confidence: "medium",
    source: "Lead form source",
  },
  {
    id: "website-mobile",
    group: "technical",
    label: "Mobile",
    status: "Unknown",
    recommendation: "Verify mobile journey evidence before classifying mobile experience.",
    evidence: "Mobile source evidence is missing in this fixture.",
    verification: "unknown",
    freshness: "unknown",
    confidence: "insufficient",
    source: "Mobile journey fixture",
  },
  {
    id: "website-visitors",
    group: "business",
    label: "Visitors",
    status: "Not connected",
    recommendation: "Connect analytics before displaying visitor counts.",
    evidence: "Visitor source is absent; no traffic number is fabricated.",
    verification: "unknown",
    freshness: "not_connected",
    confidence: "insufficient",
    source: "Visitor analytics fixture",
  },
  {
    id: "website-leads",
    group: "business",
    label: "Leads",
    status: "Current",
    recommendation: "Keep lead counts tied to verified lead-source events.",
    evidence: "Lead-source event class is current for this fixture.",
    verification: "verified",
    freshness: "current",
    confidence: "high",
    source: "Lead source fixture",
  },
  {
    id: "website-bookings",
    group: "business",
    label: "Bookings",
    status: "Unknown",
    recommendation: "Verify booking-source coverage.",
    evidence: "Booking evidence is missing in this fixture.",
    verification: "unknown",
    freshness: "unknown",
    confidence: "insufficient",
    source: "Booking source",
  },
  {
    id: "website-conversions",
    group: "business",
    label: "Conversions",
    status: "Unknown",
    recommendation: "Do not claim causation until conversion evidence and attribution are approved.",
    evidence: "Conversion-source evidence is not proven in this fixture.",
    verification: "unknown",
    freshness: "unknown",
    confidence: "insufficient",
    source: "Conversion source fixture",
  },
  {
    id: "website-high-value-pages",
    group: "business",
    label: "High-value pages",
    status: "Not connected",
    recommendation: "Connect page-value mapping before ranking pages.",
    evidence: "No page-value source is connected in this fixture.",
    verification: "unknown",
    freshness: "not_connected",
    confidence: "insufficient",
    source: "Page-value fixture",
  },
];

export const websiteFixtures = {
  loading: { state: "loading", headline: "Checking website intelligence." },
  empty: {
    state: "empty",
    headline: "No verified website activity is available.",
    description: "No activity is not treated as failure without evidence.",
  },
  unknown: { state: "unknown", headline: "Website intelligence unknown." },
  permission: { state: "permission", headline: "Website intelligence requires additional permission." },
  unavailable: { state: "unavailable", headline: "Website source unavailable." },
  partial: {
    state: "partial",
    headline: "Partial website coverage",
    coverage: "Technical journey source is current. Business outcome source is missing.",
    signals: websiteSignals,
  },
  stale: {
    state: "stale",
    headline: "Website intelligence stale",
    signals: websiteSignals,
  },
  delayed: {
    state: "delayed",
    headline: "Website processing delayed",
    signals: websiteSignals,
  },
  current: {
    state: "current",
    headline: "Critical journey review",
    signals: websiteSignals,
  },
};

export const phaseBFixtures = {
  morningBrief: morningBriefFixtures,
  businessHealth: businessHealthFixtures,
  opportunityCenter: opportunityFixtures,
  revenueIntelligence: revenueFixtures,
  websiteIntelligence: websiteFixtures,
};
