import { TrendingUp, DollarSign, Eye, CheckCircle2 } from "lucide-react";

const REVENUE_DATA = {
  totalRevenue: 47250,
  revenueThisMonth: 12840,
  leadsGenerated: 156,
  leadsConverted: 89,
  averageOrderValue: 530,
  roi: 340,
  timeRange: "Last 30 days",
};

const ATTRIBUTION_BREAKDOWN = [
  { source: "SMS Response Automation", revenue: 18900, percentage: 40, leads: 36 },
  { source: "Email Nurture Sequence", revenue: 15680, percentage: 33, leads: 29 },
  { source: "Missed Call Recovery", revenue: 8430, percentage: 18, leads: 16 },
  { source: "Booking Reminders", revenue: 4240, percentage: 9, leads: 8 },
];

const formatCurrency = (amount) => {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
  }).format(amount);
};

export default function RevenueMetricsPanel() {
  return (
    <div className="space-y-6">
      {/* Main KPIs */}
      <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-gradient-to-br from-green-50 to-emerald-50 border border-green-200 rounded-2xl p-6">
          <div className="flex items-center justify-between mb-3">
            <p className="text-xs font-semibold text-green-700 uppercase tracking-widest">Total Revenue</p>
            <DollarSign className="w-5 h-5 text-green-600" />
          </div>
          <p className="text-3xl font-bold text-green-900">{formatCurrency(REVENUE_DATA.totalRevenue)}</p>
          <p className="text-xs text-green-700/70 mt-1">Generated by ClientSurge</p>
        </div>

        <div className="bg-gradient-to-br from-blue-50 to-cyan-50 border border-blue-200 rounded-2xl p-6">
          <div className="flex items-center justify-between mb-3">
            <p className="text-xs font-semibold text-blue-700 uppercase tracking-widest">This Month</p>
            <TrendingUp className="w-5 h-5 text-blue-600" />
          </div>
          <p className="text-3xl font-bold text-blue-900">{formatCurrency(REVENUE_DATA.revenueThisMonth)}</p>
          <p className="text-xs text-blue-700/70 mt-1">vs {formatCurrency(REVENUE_DATA.revenueThisMonth * 0.85)} last month</p>
        </div>

        <div className="bg-gradient-to-br from-purple-50 to-pink-50 border border-purple-200 rounded-2xl p-6">
          <div className="flex items-center justify-between mb-3">
            <p className="text-xs font-semibold text-purple-700 uppercase tracking-widest">Leads Converted</p>
            <CheckCircle2 className="w-5 h-5 text-purple-600" />
          </div>
          <p className="text-3xl font-bold text-purple-900">
            {REVENUE_DATA.leadsConverted}/{REVENUE_DATA.leadsGenerated}
          </p>
          <p className="text-xs text-purple-700/70 mt-1">
            {Math.round((REVENUE_DATA.leadsConverted / REVENUE_DATA.leadsGenerated) * 100)}% conversion rate
          </p>
        </div>

        <div className="bg-gradient-to-br from-orange-50 to-amber-50 border border-orange-200 rounded-2xl p-6">
          <div className="flex items-center justify-between mb-3">
            <p className="text-xs font-semibold text-orange-700 uppercase tracking-widest">ROI</p>
            <TrendingUp className="w-5 h-5 text-orange-600" />
          </div>
          <p className="text-3xl font-bold text-orange-900">{REVENUE_DATA.roi}%</p>
          <p className="text-xs text-orange-700/70 mt-1">Return on investment</p>
        </div>
      </div>

      {/* Attribution Breakdown */}
      <div className="bg-card border border-border rounded-2xl overflow-hidden">
        <div className="px-6 py-4 border-b border-border">
          <h3 className="font-semibold text-foreground">Revenue by Automation</h3>
          <p className="text-xs text-muted-foreground mt-1">Which automations are driving the most revenue?</p>
        </div>

        <div className="divide-y divide-border/50">
          {ATTRIBUTION_BREAKDOWN.map((item, idx) => (
            <div key={idx} className="p-6">
              <div className="flex items-start justify-between mb-4">
                <div>
                  <h4 className="font-semibold text-foreground mb-1">{item.source}</h4>
                  <p className="text-sm text-muted-foreground">{item.leads} leads converted</p>
                </div>
                <div className="text-right">
                  <p className="text-2xl font-bold text-foreground">{formatCurrency(item.revenue)}</p>
                  <p className="text-xs text-muted-foreground">{item.percentage}% of total</p>
                </div>
              </div>

              {/* Progress bar */}
              <div className="w-full bg-muted rounded-full h-2 overflow-hidden">
                <div
                  className={`h-full transition-all ${
                    idx === 0
                      ? "bg-blue-500"
                      : idx === 1
                      ? "bg-purple-500"
                      : idx === 2
                      ? "bg-amber-500"
                      : "bg-green-500"
                  }`}
                  style={{ width: `${item.percentage}%` }}
                />
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Additional Metrics */}
      <div className="grid md:grid-cols-2 gap-4">
        <div className="bg-card border border-border rounded-2xl p-6">
          <h4 className="font-semibold text-foreground mb-4">Key Metrics</h4>
          <div className="space-y-3">
            <div className="flex justify-between items-center pb-3 border-b border-border/50">
              <span className="text-sm text-muted-foreground">Average Order Value</span>
              <span className="font-semibold text-foreground">{formatCurrency(REVENUE_DATA.averageOrderValue)}</span>
            </div>
            <div className="flex justify-between items-center pb-3 border-b border-border/50">
              <span className="text-sm text-muted-foreground">Leads Generated</span>
              <span className="font-semibold text-foreground">{REVENUE_DATA.leadsGenerated}</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-sm text-muted-foreground">Conversion Rate</span>
              <span className="font-semibold text-foreground">
                {Math.round((REVENUE_DATA.leadsConverted / REVENUE_DATA.leadsGenerated) * 100)}%
              </span>
            </div>
          </div>
        </div>

        <div className="bg-gradient-to-br from-primary/10 to-primary/5 border border-primary/20 rounded-2xl p-6">
          <h4 className="font-semibold text-foreground mb-3">Quick Insights</h4>
          <ul className="space-y-2 text-sm">
            <li className="flex items-start gap-2">
              <span className="text-primary font-bold mt-0.5">✓</span>
              <span className="text-muted-foreground">
                SMS automations are your top revenue driver at <strong className="text-foreground">40%</strong> of total revenue
              </span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-primary font-bold mt-0.5">✓</span>
              <span className="text-muted-foreground">
                Month-over-month growth of <strong className="text-foreground">+15%</strong>
              </span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-primary font-bold mt-0.5">✓</span>
              <span className="text-muted-foreground">
                Your ROI ({REVENUE_DATA.roi}%) is <strong className="text-foreground">3× higher</strong> than industry average
              </span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
}