// ⚠️ STALE — entry.ts IS THE DEPLOYED SOURCE OF TRUTH.
// This main.ts is kept for reference only. It uses shared imports that are not
// available in the deployed Deno runtime. Do NOT edit this file expecting changes
// to take effect in production. All production changes must be made to entry.ts.
import { secureJson } from "../_shared/response.ts";
import { createClientFromRequest } from "npm:@base44/sdk@0.8.25";
import { resendFetch } from "../_shared/resendFetch.js";
import { csEmailShell, csInfoCard, csPillButton, csEmailLogoUrl, CS_EMAIL_THEME, csEmailEscape } from "../_shared/clientSurgeEmailDesignSystem.ts";
import { getClientSurgeSignature, senderTags } from "../_shared/clientSurgeEmailSignatures.ts";

const IDEMPOTENCY_WINDOW_MS = 24 * 3600000;
async function wasRecentlySent(base44, leadId, stepKey) {
  const since = new Date(Date.now() - IDEMPOTENCY_WINDOW_MS).toISOString();
  const events = await base44.asServiceRole.entities.CommunicationEvent.filter({ context_id: leadId, context_type: "nurture" }, "-created_date", 10).catch(() => []);
  return (events || []).some((event) => {
    try { return JSON.parse(event.metadata_json || "{}").step_key === stepKey && event.created_date > since; }
    catch { return false; }
  });
}

function constantTimeEqual(left, right) {
  if (typeof left !== "string" || typeof right !== "string" || left.length !== right.length) return false;
  let mismatch = 0;
  for (let index = 0; index < left.length; index += 1) mismatch |= left.charCodeAt(index) ^ right.charCodeAt(index);
  return mismatch === 0;
}
function getBearerToken(req) {
  const authorization = req.headers.get("authorization") || "";
  const [scheme, token] = authorization.split(/\s+/, 2);
  if (scheme?.toLowerCase() !== "bearer" || !token) return "";
  return token.trim();
}
function allowAnonymousAutomation(req) {
  const configuredSecret = Deno.env.get("AUTOMATION_SHARED_SECRET");
  if (!configuredSecret) return true;
  const candidateSecret = req.headers.get("x-automation-secret") || getBearerToken(req);
  return constantTimeEqual(candidateSecret || "", configuredSecret);
}

const STOP_STATUSES = ["Booked", "Closed"];
const PROOF_READY_VALUES = new Set(["verified", "passed", "production_verified"]);
const STEPS = [
  { num: 1, field: "step1", daysRequired: 0, theme: "welcome" },
  { num: 2, field: "step2", daysRequired: 3, theme: "case_study_1" },
  { num: 3, field: "step3", daysRequired: 7, theme: "testimonial_1" },
  { num: 4, field: "step4", daysRequired: 10, theme: "tip_1" },
  { num: 5, field: "step5", daysRequired: 14, theme: "case_study_2" },
  { num: 6, field: "step6", daysRequired: 18, theme: "testimonial_2" },
  { num: 7, field: "step7", daysRequired: 23, theme: "tip_offer" },
  { num: 8, field: "step8", daysRequired: 30, theme: "final_cta" },
];

const EMAIL_CONTENT = {
  welcome: {
    subject: (name, biz) => `Welcome, ${name} — here's what's coming your way`,
    title: "Welcome to the ClientSurge automation series.",
    subtitle: (biz) => `Over the next 30 days, we will show what better lead response and follow-up could mean for ${biz}.`,
    cards: (name, biz) => [
      ["Why this matters", "Most service businesses lose leads because response time, follow-up, or booking handoff is too slow. ClientSurge is built to tighten that entire path."],
      ["What you'll get", "Real examples, practical tips, and clear ways to spot where your business may be losing revenue from slow or inconsistent follow-up."],
    ],
  },
  case_study_1: {
    subject: (name) => `${name}, how faster follow-up can change lead conversion`,
    title: "A real lead-response win.",
    subtitle: () => "Slow follow-up quietly kills paid traffic. Faster response changes the math.",
    cards: () => [
      ["The problem", "A med spa was getting strong leads, but many sat untouched for hours. By the time staff replied, interest had cooled."],
      ["The system", "Instant SMS response, automated Day 1 / Day 3 / Day 7 follow-up, and booking-link handoff for qualified leads."],
      ["The lesson", "Most businesses do not need more leads first. They need to convert the leads they are already paying for."],
    ],
  },
  testimonial_1: {
    subject: (name) => `${name}, most businesses underestimate lost leads`,
    title: "Most lost leads are invisible.",
    subtitle: () => "Owners often think follow-up is handled until the data proves otherwise.",
    cards: () => [
      ["Client insight", "Before automation, many leads were waiting hours for a callback. Once instant text response was added, more conversations started while interest was still high."],
      ["Audit angle", "A free automation audit shows where leads are falling through the cracks: forms, missed calls, booking handoff, or nurture."],
    ],
  },
  tip_1: {
    subject: (name) => `The 5-minute rule that changes lead response — ${name}`,
    title: "The 5-minute rule is brutal.",
    subtitle: () => "The longer a new lead waits, the colder that opportunity becomes.",
    cards: () => [
      ["What usually happens", "Staff respond when they are available, which often means leads wait 1–6 hours or longer."],
      ["What should happen", "The first response should happen automatically in under 60 seconds, every time, even after hours."],
    ],
  },
  case_study_2: {
    subject: (name) => `${name} — recovering revenue from leads already coming in`,
    title: "Recovered revenue beats buying more traffic.",
    subtitle: () => "If leads are already coming in, the fastest win is usually better capture and follow-up.",
    cards: () => [
      ["The gap", "A home-service company was paying for leads but missing calls, weekend inquiries, and form submissions."],
      ["The fix", "Missed-call text-back, after-hours auto-response, and a follow-up sequence for unbooked leads."],
      ["The takeaway", "Better response infrastructure can increase revenue without increasing ad spend."],
    ],
  },
  testimonial_2: {
    subject: (name) => `${name}, what done-for-you automation should feel like`,
    title: "Automation should not need babysitting.",
    subtitle: () => "The point is not another tool. The point is a working system.",
    cards: () => [
      ["Client expectation", "The best implementation is built, tested, and handed over running — not dumped on the business owner as another platform to manage."],
      ["ClientSurge approach", "We focus on done-for-you setup, testing, and handoff so the owner can review results instead of managing technical pieces."],
    ],
  },
  tip_offer: {
    subject: (name) => `${name} — 3 follow-up mistakes that kill conversions`,
    title: "Three follow-up mistakes that cost money.",
    subtitle: () => "These are common, fixable, and usually more expensive than owners realize.",
    cards: () => [
      ["Mistake 1", "Following up only once. Many leads need multiple touchpoints before they book."],
      ["Mistake 2", "Only calling and never texting. SMS often reaches people faster than voicemail."],
      ["Mistake 3", "Generic follow-up. Specific, relevant messages tied to the lead's problem perform better."],
    ],
  },
  final_cta: {
    subject: (name) => `${name} — last message from us`,
    title: "Last scheduled email from ClientSurge.",
    subtitle: () => "If automation is still a priority, now is the time to look at the numbers.",
    cards: () => [
      ["Bottom line", "Every day without strong follow-up is another batch of leads that can go cold."],
      ["Your choice", "Book a free audit, reply with your biggest bottleneck, or reply 'not now' and we will stop reaching out."],
    ],
  },
};

function daysSince(isoDate) {
  if (!isoDate) return 0;
  return (Date.now() - new Date(isoDate).getTime()) / (1000 * 60 * 60 * 24);
}

function getApprovedCampaignSender(settings = {}) {
  return settings.resend_from_email || Deno.env.get("RESEND_FROM_LEADS") || Deno.env.get("RESEND_FROM_EMAIL") || Deno.env.get("SUPPORT_EMAIL") || "support@clientsurgesystems.com";
}

function getCampaignSendGate() {
  const campaignEnabled = String(Deno.env.get("EMAIL_CAMPAIGN_ENABLED") || "").trim().toLowerCase() === "true";
  const proofStatus = String(Deno.env.get("EMAIL_DELIVERABILITY_PROOF_STATUS") || "").trim().toLowerCase();
  if (!campaignEnabled) return { ok: false, reason: "EMAIL_CAMPAIGN_ENABLED must be true before nurture campaign sends.", proof_status: proofStatus || "missing" };
  if (!PROOF_READY_VALUES.has(proofStatus)) return { ok: false, reason: "EMAIL_DELIVERABILITY_PROOF_STATUS must be verified before nurture campaign sends.", proof_status: proofStatus || "missing" };
  return { ok: true, proof_status: proofStatus };
}

function buildNurtureHtml({ theme, name, biz, bookingLink, adminBody }: { theme: string; name: string; biz: string; bookingLink: string; adminBody?: string }) {
  const signature = getClientSurgeSignature("sales");
  if (adminBody) {
    const renderedBody = `<p style="margin:0 0 10px;color:${CS_EMAIL_THEME.muted};font-size:15px;line-height:24px;font-weight:650;white-space:pre-wrap;">${csEmailEscape(adminBody.replace(/{name}/g, name).replace(/{business_name}/g, biz).replace(/{booking_link}/g, bookingLink))}</p>${bookingLink ? csPillButton("Book Your Free Audit →", bookingLink) : csPillButton("Visit ClientSurge Systems →", "https://clientsurgesystems.com")}`;
    return csEmailShell({ badge: "ClientSurge", title: "A quick note from ClientSurge.", subtitle: `For ${biz}`, body: renderedBody, logoUrl: csEmailLogoUrl(), footerTitle: signature.footerTitle, footerText: signature.footerText });
  }
  const content = EMAIL_CONTENT[theme] || EMAIL_CONTENT.welcome;
  const cards = content.cards(name, biz).map(([label, body], index) => csInfoCard(label, body, { accent: index === 0 })).join("");
  const cta = bookingLink ? csPillButton(theme === "final_cta" ? "Book Your Free Audit →" : "See What This Could Look Like →", bookingLink) : csPillButton("Visit ClientSurge Systems →", "https://clientsurgesystems.com");
  const unsubscribe = `<p style="margin:20px 0 0;color:${CS_EMAIL_THEME.muted};font-size:11px;line-height:17px;text-align:center;">To stop receiving emails, reply "unsubscribe".</p>`;
  return csEmailShell({ badge: "Lead Automation", title: content.title, subtitle: content.subtitle(biz), body: `${cards}${cta}${unsubscribe}`, logoUrl: csEmailLogoUrl(), footerTitle: signature.footerTitle, footerText: signature.footerText });
}

async function sendEmail(to, subject, html, resendKey, fromEmail, replyTo, tags) {
  const res = await resendFetch("https://api.resend.com/emails", {
    method: "POST",
    headers: { Authorization: `Bearer ${resendKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({ from: fromEmail, reply_to: replyTo, to, subject, html, tags }),
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err?.message || "Resend send failed");
  }
  return true;
}

Deno.serve(async (req) => {
  try {
    if (req.method !== "POST") return secureJson({ error: "Method not allowed" }, { status: 405 });
    const base44 = createClientFromRequest(req);
    let user = null;
    try { user = await base44.auth.me(); } catch (_) {}
    if (user && user.role !== "admin") return secureJson({ error: "Forbidden" }, { status: 403 });
    if (!user && !allowAnonymousAutomation(req)) return secureJson({ error: "Forbidden" }, { status: 403 });

    const campaigns = await base44.asServiceRole.entities.NurtureCampaign.filter({ status: "active" }, "-enrolled_at", 5000);
    if (!campaigns?.length) return secureJson({ success: true, processed: 0, message: "No active nurture campaigns." });

    const settingsRecords = await base44.asServiceRole.entities.AdminSettings.list("-created_date", 1);
    const settings = settingsRecords?.[0] || {};
    const resendKey = Deno.env.get("RESEND_API_KEY");
    const fromEmail = getApprovedCampaignSender(settings);
    const signature = getClientSurgeSignature("sales");
    const resendReady = !!(resendKey && settings.resend_enabled);
    if (!resendReady) return secureJson({ success: false, error: "Resend not configured. Enable Resend in Admin Settings." }, { status: 503 });

    const sendGate = getCampaignSendGate();
    if (!sendGate.ok) return secureJson({ success: false, error: "Nurture campaign sending is blocked until deliverability proof is complete.", email_sent: false, safe_to_continue: false, requires_owner_action: true, reason: sendGate.reason, proof_status: sendGate.proof_status }, { status: 403 });

    const results = { fired: 0, skipped: 0, stopped: 0, errors: 0 };

    // ── DEPLOYMENT OBSERVABILITY: Cache for per-client deployment lookups ──
    const _deploymentCache = {};

    for (const campaign of campaigns) {
      try {
        const lead = await base44.asServiceRole.entities.Leads.get(campaign.lead_id);
        if (!lead) {
          await base44.asServiceRole.entities.NurtureCampaign.update(campaign.id, { status: "stopped", stop_reason: "manual_stop", notes: "Lead not found." });
          results.stopped++;
          continue;
        }
        if (STOP_STATUSES.includes(lead.status)) {
          await base44.asServiceRole.entities.NurtureCampaign.update(campaign.id, { status: "stopped", stop_reason: lead.status === "Booked" ? "booked" : "closed" });
          results.stopped++;
          continue;
        }
        if (lead.automation_enabled === false || lead.cadence_paused === true) {
          await base44.asServiceRole.entities.NurtureCampaign.update(campaign.id, { status: "stopped", stop_reason: "opted_out", notes: "Lead opted out via SMS STOP or cadence manually paused." });
          results.stopped++;
          continue;
        }

        const daysSinceEnroll = daysSince(campaign.enrolled_at);
        const updates: any = { last_step_run_at: new Date().toISOString() };
        for (const step of STEPS) {
          const statusKey = `${step.field}_status`;
          const sentAtKey = `${step.field}_sent_at`;
          const currentStatus = campaign[statusKey];
          if (currentStatus === "sent" || currentStatus === "skipped") continue;
          if (daysSinceEnroll < step.daysRequired) { results.skipped++; continue; }
          if (await wasRecentlySent(base44, campaign.lead_id, `${campaign.id}:${step.num}`)) { results.skipped++; break; }

          const name = lead.full_name || lead.name || "there";
          const biz = lead.business_name || "your business";
          const bookingLink = settings.booking_link_default || "https://clientsurgesystems.com";
          const adminSubject = settings[`nurture_step${step.num}_subject`];
          const adminBody = settings[`nurture_step${step.num}_body`];
          const content = EMAIL_CONTENT[step.theme] || EMAIL_CONTENT.welcome;
          const subject = adminSubject ? adminSubject.replace(/{name}/g, name).replace(/{business_name}/g, biz) : content.subject(name, biz);
          const html = buildNurtureHtml({ theme: step.theme, name, biz, bookingLink, adminBody });

          let sent = false;
          let error = null;

          // ── DEPLOYMENT OBSERVABILITY: Resolve deployment + check permission ──
          let _obsCtx = null;
          if (lead.client_id && !_deploymentCache[lead.client_id]) {
            try {
              const deps = await base44.asServiceRole.entities.ClientDeployment.filter(
                { client_id: lead.client_id, deployment_status: { $in: ["live", "onboarding", "configuring", "ready"] } },
                "-created_date", 1
              );
              const dep = deps?.[0] || null;
              if (dep) {
                const permRes = await base44.asServiceRole.functions.invoke("checkModulePermission", {
                  deployment_id: dep.id, module_key: "lead_nurture",
                });
                _deploymentCache[lead.client_id] = {
                  deployment_id: dep.id,
                  authorized: permRes.data?.authorized === true,
                  reason: permRes.data?.reason,
                };
              } else { _deploymentCache[lead.client_id] = null; }
            } catch (_depErr) {
              _deploymentCache[lead.client_id] = null;
            }
          }
          const _depCtx = lead.client_id ? _deploymentCache[lead.client_id] : null;
          if (_depCtx && !_depCtx.authorized) {
            await base44.asServiceRole.functions.invoke("logAutomationExecution", {
              client_deployment_id: _depCtx.deployment_id, client_id: lead.client_id,
              module_key: "lead_nurture", trigger_event: "nurture_scheduled",
              execution_status: "blocked",
              error_message: `Module not authorized (reason: ${_depCtx.reason || "unknown"})`,
              error_code: _depCtx.reason || "module_not_authorized",
              lead_id: lead.id,
            }).catch(() => {});
            updates[statusKey] = "skipped";
            results.skipped++;
            break;
          }
          if (_depCtx) {
            _obsCtx = {
              deployment_id: _depCtx.deployment_id, client_id: lead.client_id,
              module_key: "lead_nurture", trigger_event: "nurture_scheduled",
              lead_id: lead.id,
            };
          }

          try {
            await sendEmail(lead.email || campaign.lead_email, subject, html, resendKey, fromEmail, signature.replyTo, senderTags("sales", `nurture_step_${step.num}`));
            sent = true;
            // ── DEPLOYMENT OBSERVABILITY: Log successful execution ──
            if (_obsCtx) {
              await base44.asServiceRole.functions.invoke("logAutomationExecution", {
                ..._obsCtx, execution_status: "completed",
                response_data: JSON.stringify({ step: step.num, theme: step.theme }),
              }).catch(() => {});
            }
          } catch (err) {
            error = err.message;
            console.error(`[processNurtureCampaigns] step${step.num} error for ${campaign.lead_id}:`, err.message);
            // ── DEPLOYMENT OBSERVABILITY: Log failed execution ──
            if (_obsCtx) {
              await base44.asServiceRole.functions.invoke("logAutomationExecution", {
                ..._obsCtx, execution_status: "failed",
                error_message: error, error_code: "resend_send_failed",
              }).catch(() => {});
            }
          }

          updates[statusKey] = sent ? "sent" : "failed";
          if (sent) updates[sentAtKey] = new Date().toISOString();
          updates.current_step = step.num;
          await base44.asServiceRole.entities.CommunicationEvent.create({ lead_id: campaign.lead_id, channel: "email", direction: "outbound", event_type: "email_sent", provider: "resend", status: sent ? "sent" : "failed", subject: `Nurture Step ${step.num} — ${subject}`, message_body: `Nurture email (Day ${step.daysRequired}, theme: ${step.theme})`, error_message: error || undefined, context_id: campaign.lead_id, context_type: "nurture", metadata_json: JSON.stringify({ nurture_step: step.num, campaign_id: campaign.id, theme: step.theme, step_key: `${campaign.id}:${step.num}`, sender_identity: "sales" }) });
          sent ? results.fired++ : results.errors++;
          break;
        }

        const allSent = STEPS.every((s) => {
          const v = updates[`${s.field}_status`] ?? campaign[`${s.field}_status`];
          return v === "sent" || v === "skipped";
        });
        if (allSent) {
          updates.status = "completed";
          updates.stop_reason = "completed_all_steps";
        }
        await base44.asServiceRole.entities.NurtureCampaign.update(campaign.id, updates);
      } catch (err) {
        console.error("[processNurtureCampaigns] campaign error", err.message);
        results.errors++;
      }
    }

    return secureJson({ success: true, ...results });
  } catch (error) {
    console.error("[processNurtureCampaigns]", error.message);
    return secureJson({ error: error.message }, { status: 500 });
  }
});