import { secureJson } from "../_shared/response.ts";
import { createClientFromRequest } from "npm:@base44/sdk@0.8.25";

const CONFIRM_PHRASE = "GENERATE QA LEAD PROOF";

function runId(now = new Date()) {
  return `qa-lead-proof-${now.toISOString().replace(/[:.]/g, "-")}`;
}

function buildFixtures(id: string, now: string) {
  const shared = {
    run_id: id,
    generated_at: now,
    source: "qa_lead_proof_generator",
    consent_source: "qa_lead_proof_generator",
    source_page: "admin_qa_tools",
    automation_enabled: false,
    cadence_paused: true,
    cadence_paused_at: now,
  };

  return [
    {
      key: "website_internal_marker",
      entity: "WebsiteLead",
      expected_bucket: "hidden_archived_ignored",
      data: {
        ...shared,
        business_name: `Install Test — ClientSurge Proof ${id}`,
        full_name: "ClientSurge QA Proof",
        first_name: "QA",
        email: `test+${id}@clientsurge-install.internal`,
        phone_number: "+16025550100",
        business_type: "test",
        service_interest: "QA proof only",
        message: "Generated by QA Lead Proof Generator. Do not contact.",
        lead_status: "ignored",
        reply_status: "none",
        booking_status: "none",
        archived: true,
        archived_at: now,
        quality_notes: `qa_lead_proof:${id}:internal_marker`,
      },
    },
    {
      key: "lead_quarantine_marker",
      entity: "Leads",
      expected_bucket: "quarantine_candidate",
      data: {
        business_name: `ClientSurge Smoke QA ${id}`,
        full_name: "ClientSurge QA Proof",
        email: `qa+${id}@clientsurge.test`,
        phone: "+16025550101",
        website: "https://clientsurge.test",
        business_type: "test",
        city: "Phoenix",
        state: "AZ",
        source: "qa_lead_proof_generator",
        quality_review_status: "quarantine_candidate",
        quality_reason: `QA lead proof generator internal/test marker ${id}`,
        quality_reason_codes: ["internal_test", "example_email", "test_phone_555", "test_website", "qa_lead_proof_generator"],
        quality_confidence: 99,
        audited_at: now,
        lead_state: "NEW",
        status: "New",
      },
    },
    {
      key: "lead_duplicate_marker_a",
      entity: "Leads",
      expected_bucket: "duplicate_candidate",
      data: {
        business_name: `QA Duplicate Dental ${id}`,
        full_name: "QA Duplicate One",
        email: `qa-duplicate-a+${id}@clientsurge.test`,
        phone: "+16025550102",
        website: "https://qa-duplicate.clientsurge.test",
        business_type: "Dental",
        city: "Phoenix",
        state: "AZ",
        source: "qa_lead_proof_generator",
        dedupe_status: "duplicate_candidate",
        dedupe_group_key: `qa-proof-duplicate:${id}`,
        quality_review_status: "duplicate_candidate",
        quality_reason: `QA duplicate proof group: ${id}`,
        quality_reason_codes: ["duplicate_candidate", "qa_lead_proof_generator"],
        quality_confidence: 95,
        audited_at: now,
      },
    },
    {
      key: "lead_duplicate_marker_b",
      entity: "Leads",
      expected_bucket: "duplicate_candidate",
      data: {
        business_name: `QA Duplicate Dental ${id}`,
        full_name: "QA Duplicate Two",
        email: `qa-duplicate-b+${id}@clientsurge.test`,
        phone: "+16025550102",
        website: "https://qa-duplicate.clientsurge.test",
        business_type: "Dental",
        city: "Phoenix",
        state: "AZ",
        source: "qa_lead_proof_generator",
        dedupe_status: "duplicate_candidate",
        dedupe_group_key: `qa-proof-duplicate:${id}`,
        quality_review_status: "duplicate_candidate",
        quality_reason: `QA duplicate proof group: ${id}`,
        quality_reason_codes: ["duplicate_candidate", "qa_lead_proof_generator"],
        quality_confidence: 95,
        audited_at: now,
      },
    },
    {
      key: "lead_no_contact_marker",
      entity: "Leads",
      expected_bucket: "blocked_missing_contact",
      data: {
        business_name: `QA Raw Import No Contact ${id}`,
        full_name: "QA No Contact",
        business_type: "Unknown",
        city: "",
        state: "",
        source: "qa_lead_proof_generator",
        quality_review_status: "quarantine_candidate",
        quality_reason: `QA raw import no contact proof ${id}`,
        quality_reason_codes: ["raw_import_no_contact", "missing_city_state_no_contact", "qa_lead_proof_generator"],
        quality_confidence: 98,
        audited_at: now,
      },
    },
  ];
}

function summarize(fixtures: any[]) {
  return fixtures.reduce((acc, fixture) => {
    acc.total += 1;
    acc.by_entity[fixture.entity] = (acc.by_entity[fixture.entity] || 0) + 1;
    acc.expected_buckets[fixture.expected_bucket] = (acc.expected_buckets[fixture.expected_bucket] || 0) + 1;
    return acc;
  }, { total: 0, by_entity: {}, expected_buckets: {} });
}

Deno.serve(async (req) => {
  try {
    if (req.method !== "POST") {
      return secureJson({ success: false, error: "Method not allowed" }, { status: 405 });
    }

    const base44 = createClientFromRequest(req);
    let user: any = null;
    try {
      user = await base44.auth.me();
    } catch (_) {}
    if (!user || !["admin", "super_admin"].includes(user.role)) {
      return secureJson({ success: false, error: "Admin access required" }, { status: 403 });
    }

    const body = await req.json().catch(() => ({}));
    const apply = body.apply === true;
    const confirmed = body.confirm_phrase === CONFIRM_PHRASE;
    const now = new Date().toISOString();
    const id = body.run_id || runId(new Date(now));
    const fixtures = buildFixtures(id, now);

    if (!apply) {
      return secureJson({
        success: true,
        dry_run: true,
        run_id: id,
        confirm_phrase: CONFIRM_PHRASE,
        summary: summarize(fixtures),
        fixtures: fixtures.map(({ key, entity, expected_bucket, data }) => ({
          key,
          entity,
          expected_bucket,
          preview_name: data.business_name || data.full_name || data.email,
        })),
      });
    }

    if (!confirmed) {
      return secureJson({ success: false, error: `Apply mode requires confirm_phrase ${CONFIRM_PHRASE}` }, { status: 400 });
    }

    const created: any[] = [];
    const failed: any[] = [];

    for (const fixture of fixtures) {
      try {
        const entityApi = fixture.entity === "WebsiteLead"
          ? base44.asServiceRole.entities.WebsiteLead
          : base44.asServiceRole.entities.Leads;
        const record = await entityApi.create(fixture.data);
        created.push({ key: fixture.key, entity: fixture.entity, id: record?.id, expected_bucket: fixture.expected_bucket });
      } catch (error: any) {
        failed.push({ key: fixture.key, entity: fixture.entity, error: error?.message || "create failed" });
      }
    }

    await base44.asServiceRole.entities.CommunicationEvent.create({
      channel: "internal",
      direction: "system",
      event_type: "qa_lead_proof_generated",
      provider: "generateQaLeadProofSet",
      status: failed.length ? "partial" : "completed",
      subject: "QA lead proof fixture set generated",
      message_body: `Created ${created.length} QA proof record(s); failed ${failed.length}.`,
      context_type: "qa_lead_proof",
      context_id: id,
      metadata_json: JSON.stringify({ run_id: id, created, failed, summary: summarize(fixtures), generated_at: now }),
    }).catch(() => null);

    return secureJson({
      success: failed.length === 0,
      dry_run: false,
      run_id: id,
      summary: summarize(fixtures),
      created,
      failed,
    });
  } catch (error: any) {
    return secureJson({ success: false, error: error?.message || "QA lead proof generation failed" }, { status: 500 });
  }
});
