export const PHASE_C_AI_WORKFORCE_STATES = [
  "loading",
  "current",
  "healthy",
  "degraded",
  "attention_required",
  "blocked",
  "paused",
  "offline",
  "unknown",
  "unavailable",
  "not_configured",
];

export const PHASE_C_STATE_MATRIX = {
  aiWorkforce: PHASE_C_AI_WORKFORCE_STATES,
  clientTimeline: ["normal", "delayed", "restricted", "empty"],
  communicationCenter: ["unread", "failed", "escalated", "permission_restricted"],
  customerSuccess: ["healthy", "risk", "missing_data", "incomplete_setup"],
};

const fixtureTime = "2026-07-20T08:40:00-07:00";
const fixtureScope = "Static Phase C review fixture";

export const phaseCDisclosure = {
  source: "Static Phase C review fixture",
  sourceId: "phase-c-static-fixture",
  truth: "reported",
  freshness: "current",
  timestamp: fixtureTime,
  scope: fixtureScope,
  permission: "customer_success_review",
  explanation: "This route is a review-only foundation. It is not connected to production data.",
};

const workerEvidence = [
  { id: "worker-evidence-call", label: "Missed-call source event exists in the fixture." },
  { id: "worker-evidence-message", label: "Drafted reply is linked to the related conversation." },
  { id: "worker-evidence-owner", label: "Human handoff queue is visible before any resolution claim." },
];

const baseWorker = {
  id: "ai-receptionist",
  identity: "AI Receptionist",
  role: "Lead response and booking support",
  responsibility: "Triage missed calls, prepare replies, and route booking-ready leads.",
  currentStatus: "Current work is reviewable",
  configurationState: "Configured for missed-call follow-up",
  recentWork: "Prepared two reply drafts for missed-call review.",
  completedWork: "Classified one caller as booking-ready in the fixture.",
  businessResult: "A human can inspect the caller context before a reply is sent.",
  blockedWork: "No blocked work in this state.",
  evidence: workerEvidence,
  confidence: "medium",
  freshness: "current",
  truth: "reported",
  recommendation: "Review the prepared reply and approve the next customer-safe action.",
  owner: "ai_worker",
  handoff: {
    reason: "Human approval is required before external communication.",
    target: "ClientSurge staff",
    urgency: "Today",
    context: "Caller asked about same-day availability.",
  },
};

const aiWorkerStateCopy = {
  loading: {
    status: "Loading",
    tone: "info",
    happening: "Checking worker assignment, configuration, and recent work before any status claim is shown.",
    attention: "No worker result is promoted while the fixture is loading.",
    nextAction: "Wait for the worker evidence panel to finish loading.",
    worker: {
      ...baseWorker,
      currentStatus: "Loading worker evidence",
      configurationState: "Configuration check pending",
      recentWork: "Recent work is not displayed until the review fixture resolves.",
      completedWork: "Completed work is not displayed while loading.",
      businessResult: "No result is claimed before source review completes.",
      confidence: "insufficient",
      freshness: "unknown",
      truth: "unknown",
    },
  },
  current: {
    status: "Current",
    tone: "success",
    happening: "Worker evidence is current for the review fixture.",
    attention: "One drafted reply still needs human approval before customer contact.",
    nextAction: "Open the handoff context and approve or revise the reply.",
    worker: baseWorker,
  },
  healthy: {
    status: "Healthy",
    tone: "success",
    happening: "The worker has current evidence, visible output, and an owner for the next decision.",
    attention: "No blocker exists, but the reply still requires human approval.",
    nextAction: "Review the recommendation before approving outreach.",
    worker: {
      ...baseWorker,
      currentStatus: "Healthy with current evidence",
      completedWork: "Prepared replies and classified booking intent for review.",
      blockedWork: "No blocked work in this state.",
      confidence: "high",
    },
  },
  degraded: {
    status: "Degraded",
    tone: "warning",
    happening: "The worker can prepare replies, but booking context is incomplete.",
    attention: "Booking-source coverage is partial.",
    nextAction: "Verify booking-source coverage before approving the suggested reply.",
    worker: {
      ...baseWorker,
      currentStatus: "Degraded by partial booking evidence",
      blockedWork: "Booking availability source is partial.",
      businessResult: "The caller can still be triaged, but availability cannot be confirmed.",
      confidence: "low",
      freshness: "partial",
      recommendation: "Confirm availability source coverage before replying.",
    },
  },
  attention_required: {
    status: "Attention required",
    tone: "warning",
    happening: "The worker found a lead response path that needs human review.",
    attention: "The reply cannot be sent until ownership is accepted.",
    nextAction: "Accept the handoff and review the draft.",
    worker: {
      ...baseWorker,
      currentStatus: "Attention required",
      blockedWork: "Human ownership has not been accepted.",
      recommendation: "Assign the reply review to a named owner.",
      owner: "unassigned",
    },
  },
  blocked: {
    status: "Blocked",
    tone: "danger",
    happening: "The worker cannot complete the next step because messaging setup is incomplete.",
    attention: "Customer-facing outreach is blocked.",
    nextAction: "Open messaging setup before approving any reply.",
    worker: {
      ...baseWorker,
      currentStatus: "Blocked by messaging setup",
      configurationState: "Messaging approval not configured",
      completedWork: "Caller context was summarized but not sent.",
      businessResult: "No customer message has been sent from this fixture.",
      blockedWork: "Outbound SMS channel is not configured.",
      confidence: "medium",
      freshness: "not_connected",
      recommendation: "Complete messaging setup, then retry the handoff.",
    },
  },
  paused: {
    status: "Paused",
    tone: "neutral",
    happening: "The worker is intentionally paused by an authorized actor.",
    attention: "Paused is not an error, but new work will not be handled automatically.",
    nextAction: "Confirm whether the pause is still intended.",
    worker: {
      ...baseWorker,
      currentStatus: "Paused by ClientSurge staff",
      configurationState: "Enabled but paused",
      recentWork: "No new work while paused.",
      completedWork: "Previous completed work remains visible.",
      blockedWork: "Automation is intentionally stopped.",
      recommendation: "Resume only after confirming owner intent.",
      owner: "clientsurge_staff",
    },
  },
  offline: {
    status: "Offline",
    tone: "danger",
    happening: "A previously configured worker is not operating.",
    attention: "New missed calls are not being triaged by this worker.",
    nextAction: "Inspect worker connectivity and route work to a human queue.",
    worker: {
      ...baseWorker,
      currentStatus: "Offline",
      configurationState: "Previously configured",
      recentWork: "No current work is being processed.",
      completedWork: "Last completed work remains visible for audit.",
      businessResult: "Human queue should cover missed-call follow-up until service returns.",
      blockedWork: "Worker runtime is offline.",
      confidence: "insufficient",
      freshness: "unavailable",
      recommendation: "Escalate to ClientSurge staff and use the human queue.",
    },
  },
  unknown: {
    status: "Unknown",
    tone: "neutral",
    happening: "The worker status cannot be verified from available evidence.",
    attention: "Unknown is not treated as healthy.",
    nextAction: "Check source permissions and retry the worker status review.",
    worker: {
      ...baseWorker,
      currentStatus: "Unknown",
      configurationState: "Configuration not verified",
      recentWork: "Recent work is not verified.",
      completedWork: "Completed work is not verified.",
      businessResult: "No business result is claimed.",
      blockedWork: "Unknown because source evidence is insufficient.",
      confidence: "insufficient",
      freshness: "unknown",
      truth: "unknown",
      recommendation: "Verify worker evidence before acting.",
    },
  },
  unavailable: {
    status: "Unavailable",
    tone: "danger",
    happening: "Worker evidence cannot currently be retrieved.",
    attention: "The customer cannot rely on worker output while the source is unavailable.",
    nextAction: "Use the human fallback and retry source verification.",
    worker: {
      ...baseWorker,
      currentStatus: "Unavailable",
      configurationState: "Configuration cannot be retrieved",
      recentWork: "Recent work source is unavailable.",
      completedWork: "Completed work source is unavailable.",
      businessResult: "No current business result is displayed.",
      blockedWork: "Worker source unavailable.",
      confidence: "insufficient",
      freshness: "unavailable",
      truth: "unknown",
      recommendation: "Retry source verification before approving output.",
    },
  },
  not_configured: {
    status: "Not configured",
    tone: "neutral",
    happening: "The worker has not been configured for this customer.",
    attention: "Not configured is distinct from offline.",
    nextAction: "Open worker configuration before expecting automated work.",
    worker: {
      ...baseWorker,
      currentStatus: "Not configured",
      configurationState: "Setup incomplete",
      recentWork: "No recent work exists because setup has not completed.",
      completedWork: "No completed work exists for this worker.",
      businessResult: "No automated lead response result is claimed.",
      blockedWork: "Worker setup is incomplete.",
      confidence: "insufficient",
      freshness: "not_connected",
      truth: "unknown",
      recommendation: "Complete worker configuration and assign an owner.",
    },
  },
};

export const aiWorkforceFixtures = Object.fromEntries(
  Object.entries(aiWorkerStateCopy).map(([state, item]) => [
    state,
    {
      system: "aiWorkforce",
      state,
      title: "AI Workforce OS",
      subtitle: "Worker output is shown as business work, evidence, ownership, and handoff context.",
      disclosure: {
        ...phaseCDisclosure,
        truth: item.worker.truth || "reported",
        freshness: item.worker.freshness || "current",
      },
      recommendations: [
        {
          id: `worker-rec-${state}`,
          title: item.worker.recommendation,
          reason: item.attention,
          evidence: item.worker.evidence,
          priority: state === "blocked" || state === "offline" ? "critical" : "high",
          owner: item.worker.owner,
          expectedResult: "Customer-facing work has a named owner and auditable next step.",
          destination: "AI Workforce > Human handoff",
          lifecycle: state === "healthy" || state === "current" ? "new" : "waiting_on_dependency",
          confidence: item.worker.confidence,
          truth: item.worker.truth,
          freshness: item.worker.freshness,
        },
      ],
      ...item,
    },
  ]),
);

const timelineCategories = [
  ["customer", "Customer", "Customer asked for same-day availability"],
  ["human", "Human", "ClientSurge staff accepted the handoff"],
  ["ai", "AI", "AI Receptionist drafted a reply"],
  ["system", "System", "Routing rule evaluated the lead source"],
  ["communication", "Communication", "SMS draft was prepared for approval"],
  ["appointment", "Appointment", "AI Receptionist booked appointment after approval"],
  ["payment", "Payment", "Payment source reported setup incomplete"],
  ["website", "Website", "Lead form source reported conversion context"],
  ["configuration", "Configuration", "Messaging setup changed from pending to review"],
  ["status", "Status change", "Lead lifecycle changed to waiting on approval"],
  ["support", "Support", "Support note added for messaging setup"],
];

export const timelineEvents = timelineCategories.map(([id, category, summary], index) => ({
  id: `evt-phase-c-${String(index + 1).padStart(3, "0")}`,
  category,
  timestamp: `2026-07-20T0${Math.min(index + 1, 9)}:20:00-07:00`,
  source: `${category} review source`,
  actor: category === "AI" ? "AI Receptionist" : category === "Human" ? "ClientSurge staff" : "ClientSurge system",
  verification: index < 6 ? "verified" : index < 9 ? "reported" : "unknown",
  freshness: index < 7 ? "current" : "delayed",
  businessSummary: summary,
  relatedObject: index % 2 === 0 ? "Lead L-2048" : "Conversation C-1182",
  permissionScope: "Visible to customer success and account owner",
  deepLink: `#timeline-${id}`,
}));

export const timelineFixtures = {
  normal: {
    system: "clientTimeline",
    state: "normal",
    title: "Client Timeline",
    subtitle: "Unified events keep actor, source, permission, and related object intact.",
    status: "Normal",
    tone: "success",
    happening: "Verified events are ordered with source and actor provenance visible.",
    attention: "No event is flattened into a generic activity label.",
    nextAction: "Open the highest-priority event to inspect the related object.",
    disclosure: { ...phaseCDisclosure, truth: "reported", freshness: "current" },
    events: timelineEvents,
  },
  delayed: {
    system: "clientTimeline",
    state: "delayed",
    title: "Client Timeline",
    subtitle: "Delayed sources stay visible without being promoted to current.",
    status: "Delayed",
    tone: "warning",
    happening: "Communication and payment events are delayed by their sources.",
    attention: "The timeline is useful for review but not current enough for final audit claims.",
    nextAction: "Filter to delayed events and inspect the affected source.",
    disclosure: { ...phaseCDisclosure, truth: "reported", freshness: "delayed" },
    events: timelineEvents.map((event) => ({ ...event, freshness: event.category === "Communication" || event.category === "Payment" ? "delayed" : event.freshness })),
  },
  restricted: {
    system: "clientTimeline",
    state: "restricted",
    title: "Client Timeline",
    subtitle: "Restricted events do not leak protected details.",
    status: "Permission restricted",
    tone: "warning",
    happening: "Some events may exist but are outside the current role permission scope.",
    attention: "Counts and summaries avoid leaking restricted content.",
    nextAction: "Request customer success permission or continue with visible events.",
    disclosure: { ...phaseCDisclosure, truth: "unknown", freshness: "permission_restricted" },
    events: timelineEvents.slice(0, 5).map((event) => ({ ...event, permissionScope: "Restricted details withheld for this role" })),
  },
  empty: {
    system: "clientTimeline",
    state: "empty",
    title: "Client Timeline",
    subtitle: "Empty state explains why no events are visible.",
    status: "Empty valid",
    tone: "neutral",
    happening: "No events match the selected fixture filters.",
    attention: "This does not mean no customer activity exists outside the selected scope.",
    nextAction: "Clear filters or inspect source coverage.",
    disclosure: { ...phaseCDisclosure, truth: "verified", freshness: "current" },
    events: [],
  },
};

export const conversations = [
  {
    id: "conv-sms-1182",
    channel: "SMS",
    customer: "Maya Ortiz",
    subject: "Same-day appointment request",
    unread: true,
    unresolved: true,
    owner: "clientsurge_staff",
    assignment: "ClientSurge response queue",
    state: "Delivered",
    lastStatus: "Delivered but not read",
    aiAssistance: "AI drafted a reply but did not send it.",
    escalation: "Human approval required",
    permission: "Customer success can view and reply",
    nextAction: "Review draft reply",
    evidence: [
      { id: "sms-status", label: "Delivery receipt exists; read receipt does not." },
      { id: "sms-draft", label: "AI draft is linked to this conversation." },
    ],
  },
  {
    id: "conv-email-4421",
    channel: "Email",
    customer: "North Valley Dental",
    subject: "Installation checklist",
    unread: false,
    unresolved: true,
    owner: "customer",
    assignment: "Account owner",
    state: "Sent",
    lastStatus: "Sent, delivery not verified",
    aiAssistance: "AI summarized missing setup context.",
    escalation: "Waiting on account owner",
    permission: "Visible to account owner and ClientSurge staff",
    nextAction: "Confirm delivery before assuming customer received it",
    evidence: [
      { id: "email-sent", label: "Send record exists." },
      { id: "email-delivery", label: "Delivery record is not available in this fixture." },
    ],
  },
  {
    id: "conv-voice-8077",
    channel: "Voice",
    customer: "Dr. Patel",
    subject: "Voicemail follow-up",
    unread: true,
    unresolved: false,
    owner: "ai_worker",
    assignment: "AI Receptionist",
    state: "Read",
    lastStatus: "Voicemail listened to by authorized user",
    aiAssistance: "AI extracted callback intent.",
    escalation: "No escalation active",
    permission: "Call details visible to assigned owner",
    nextAction: "Log callback outcome",
    evidence: [
      { id: "voice-read", label: "Voicemail playback event is present." },
    ],
  },
];

export const communicationFixtures = {
  unread: {
    system: "communicationCenter",
    state: "unread",
    title: "Communication Center",
    subtitle: "Unified conversations distinguish sent, delivered, read, failed, blocked, and unknown states.",
    status: "Unread conversations",
    tone: "warning",
    happening: "Unread customer messages and unresolved owner queues are visible.",
    attention: "Delivered is not treated as read, and sent is not treated as delivered.",
    nextAction: "Review the unread SMS draft and accept ownership.",
    disclosure: { ...phaseCDisclosure, truth: "reported", freshness: "current" },
    conversations,
  },
  failed: {
    system: "communicationCenter",
    state: "failed",
    title: "Communication Center",
    subtitle: "Failed communication states include consequence and recovery path.",
    status: "Failed",
    tone: "danger",
    happening: "An outbound message failed before delivery.",
    attention: "The customer may not have received the response.",
    nextAction: "Open delivery recovery and choose a safe retry path.",
    disclosure: { ...phaseCDisclosure, truth: "reported", freshness: "current" },
    conversations: conversations.map((item, index) => index === 0 ? { ...item, state: "Failed", lastStatus: "Send failed before delivery", nextAction: "Retry after channel check" } : item),
  },
  escalated: {
    system: "communicationCenter",
    state: "escalated",
    title: "Communication Center",
    subtitle: "Escalations make AI assistance and human ownership explicit.",
    status: "Escalated",
    tone: "warning",
    happening: "AI assistance escalated a customer reply to a human queue.",
    attention: "The escalation should not silently disappear.",
    nextAction: "Accept or reassign the escalated conversation.",
    disclosure: { ...phaseCDisclosure, truth: "reported", freshness: "current" },
    conversations: conversations.map((item, index) => index === 0 ? { ...item, escalation: "Escalated to human owner", assignment: "Unassigned support queue", owner: "unassigned" } : item),
  },
  permission_restricted: {
    system: "communicationCenter",
    state: "permission_restricted",
    title: "Communication Center",
    subtitle: "Permission restricted conversations do not leak protected content.",
    status: "Permission restricted",
    tone: "warning",
    happening: "Conversation existence may be restricted by role.",
    attention: "Restricted content is not shown as zero conversations.",
    nextAction: "Request access or continue with visible messages.",
    disclosure: { ...phaseCDisclosure, truth: "unknown", freshness: "permission_restricted" },
    conversations: conversations.slice(0, 1).map((item) => ({ ...item, subject: "Restricted conversation details withheld", permission: "Protected details withheld" })),
  },
};

const successRisks = [
  {
    id: "risk-installation",
    title: "Installation progress needs owner review",
    evidence: "Messaging setup is incomplete in the fixture.",
    reason: "Automation coverage cannot be considered complete until messaging is approved.",
    impact: "Missed-call follow-up may remain manual.",
    owner: "clientsurge_staff",
    nextAction: "Open installation checklist",
    priority: "high",
  },
  {
    id: "risk-adoption",
    title: "AI usage requires customer enablement",
    evidence: "AI worker recommendations exist but have not been accepted.",
    reason: "The customer has not completed the first human handoff review.",
    impact: "The AI worker may not create visible business value yet.",
    owner: "customer",
    nextAction: "Schedule handoff walkthrough",
    priority: "medium",
  },
];

const successPlan = [
  { id: "plan-install", label: "Complete installation", owner: "clientsurge_staff", state: "In progress" },
  { id: "plan-adoption", label: "Approve first AI handoff", owner: "customer", state: "Waiting on customer" },
  { id: "plan-renewal", label: "Review renewal readiness", owner: "clientsurge_staff", state: "Not assessed" },
];

export const customerSuccessFixtures = {
  healthy: {
    system: "customerSuccess",
    state: "healthy",
    title: "Customer Success Workspace",
    subtitle: "The workspace uses evidence-backed qualitative status, not unsupported health scores.",
    status: "Healthy",
    tone: "success",
    happening: "Installation and adoption evidence is current for the review fixture.",
    attention: "No risk is promoted without evidence.",
    nextAction: "Review the next success-plan intervention.",
    disclosure: { ...phaseCDisclosure, truth: "reported", freshness: "current" },
    overview: {
      installation: "Installation checklist current",
      adoption: "First AI handoff reviewed",
      automationCoverage: "Messaging and booking fixtures available",
      aiUsage: "AI recommendations visible with owner and evidence",
      renewalReadiness: "Qualitative readiness only; no score is shown",
      accountOwner: "ClientSurge success manager",
    },
    risks: [],
    successPlan,
  },
  risk: {
    system: "customerSuccess",
    state: "risk",
    title: "Customer Success Workspace",
    subtitle: "Every risk includes evidence, reason, impact, owner, and next action.",
    status: "Risk signals",
    tone: "warning",
    happening: "Two evidence-backed risks need account owner attention.",
    attention: "Messaging setup and AI adoption are not complete.",
    nextAction: "Assign the installation intervention before routine review.",
    disclosure: { ...phaseCDisclosure, truth: "reported", freshness: "current" },
    overview: {
      installation: "Messaging setup incomplete",
      adoption: "First AI handoff not accepted",
      automationCoverage: "Partial automation coverage",
      aiUsage: "Recommendations exist but are not accepted",
      renewalReadiness: "Renewal readiness cannot be scored",
      accountOwner: "ClientSurge success manager",
    },
    risks: successRisks,
    successPlan,
  },
  missing_data: {
    system: "customerSuccess",
    state: "missing_data",
    title: "Customer Success Workspace",
    subtitle: "Missing data is visible and not converted into healthy or zero.",
    status: "Missing data",
    tone: "warning",
    happening: "Adoption and AI usage sources are missing from the fixture.",
    attention: "The workspace cannot classify customer success without source coverage.",
    nextAction: "Open source coverage and request missing permissions.",
    disclosure: { ...phaseCDisclosure, truth: "unknown", freshness: "unknown" },
    overview: {
      installation: "Installation source current",
      adoption: "Adoption source missing",
      automationCoverage: "Coverage incomplete",
      aiUsage: "AI usage source missing",
      renewalReadiness: "Not assessed because data is missing",
      accountOwner: "ClientSurge success manager",
    },
    risks: [successRisks[0]],
    successPlan,
  },
  incomplete_setup: {
    system: "customerSuccess",
    state: "incomplete_setup",
    title: "Customer Success Workspace",
    subtitle: "Incomplete setup explains the blocker and owner before any status claim.",
    status: "Incomplete setup",
    tone: "neutral",
    happening: "The customer success workspace has not completed installation setup.",
    attention: "Automation coverage and renewal readiness are not assessable.",
    nextAction: "Complete installation setup before judging adoption.",
    disclosure: { ...phaseCDisclosure, truth: "reported", freshness: "not_connected" },
    overview: {
      installation: "Setup incomplete",
      adoption: "Not started",
      automationCoverage: "Not connected",
      aiUsage: "Not configured",
      renewalReadiness: "Not assessable",
      accountOwner: "ClientSurge success manager",
    },
    risks: [successRisks[0]],
    successPlan,
  },
};

export const phaseCFixtures = {
  aiWorkforce: aiWorkforceFixtures,
  clientTimeline: timelineFixtures,
  communicationCenter: communicationFixtures,
  customerSuccess: customerSuccessFixtures,
};
