// ⚠️ STALE — entry.ts IS THE DEPLOYED SOURCE OF TRUTH.
// This main.ts is kept for reference only. It uses shared imports that are not
// available in the deployed Deno runtime. Do NOT edit this file expecting changes
// to take effect in production. All production changes must be made to entry.ts.
import { secureJson } from "../_shared/response.ts";
import { createClientFromRequest } from "npm:@base44/sdk@0.8.25";
import { resendFetch } from "../_shared/resendFetch.js";
import { csEmailShell, csEmailFrom, csEmailLogoUrl, csEmailEscape, CS_EMAIL_THEME } from "../_shared/clientSurgeEmailDesignSystem.ts";

function allowAnonymousAutomation(req) {
  const ua = req.headers.get("user-agent") || "";
  const auth = req.headers.get("authorization") || "";
  return ua.includes("base44") || auth.startsWith("Bearer ");
}

const LEAD_LIMIT = 5000;
const BUSINESS_TZ = "America/Phoenix";
const PHOENIX_OFFSET = "-07:00";

function getPhoenixDayStart(reference = new Date()) {
  const parts = new Intl.DateTimeFormat("en-CA", { timeZone: BUSINESS_TZ, year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(reference);
  const year = parts.find((part) => part.type === "year")?.value;
  const month = parts.find((part) => part.type === "month")?.value;
  const day = parts.find((part) => part.type === "day")?.value;
  return new Date(`${year}-${month}-${day}T00:00:00${PHOENIX_OFFSET}`);
}

function formatPhoenixDate(reference = new Date()) {
  return reference.toLocaleDateString("en-US", { timeZone: BUSINESS_TZ });
}

function metricCard(label: string, value: number, detail: string) {
  return `<td style="width:50%;padding:6px;vertical-align:top;"><div style="background:${CS_EMAIL_THEME.soft};border:1px solid ${CS_EMAIL_THEME.border};border-radius:16px;padding:18px 16px;text-align:center;"><div style="font-size:32px;line-height:38px;font-weight:900;color:#000;">${value}</div><div style="margin-top:4px;color:${CS_EMAIL_THEME.deep};font-size:11px;line-height:15px;font-weight:900;text-transform:uppercase;letter-spacing:0.08em;">${csEmailEscape(label)}</div><div style="margin-top:5px;color:${CS_EMAIL_THEME.muted};font-size:12px;line-height:17px;font-weight:700;">${csEmailEscape(detail)}</div></div></td>`;
}

function hotLeadTable(rows: string) {
  if (!rows) return "";
  return `<div style="margin-top:24px;background:#ffffff;border:1px solid ${CS_EMAIL_THEME.border};border-radius:16px;padding:20px 22px;"><div style="color:${CS_EMAIL_THEME.deep};font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:0.09em;margin-bottom:12px;">Top Hot Leads</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;font-size:13px;"><thead><tr><th style="padding:8px 10px;text-align:left;border-bottom:1px solid ${CS_EMAIL_THEME.border};color:${CS_EMAIL_THEME.muted};">Name</th><th style="padding:8px 10px;text-align:left;border-bottom:1px solid ${CS_EMAIL_THEME.border};color:${CS_EMAIL_THEME.muted};">Business</th><th style="padding:8px 10px;text-align:left;border-bottom:1px solid ${CS_EMAIL_THEME.border};color:${CS_EMAIL_THEME.muted};">Status</th><th style="padding:8px 10px;text-align:left;border-bottom:1px solid ${CS_EMAIL_THEME.border};color:${CS_EMAIL_THEME.muted};">Score</th></tr></thead><tbody>${rows}</tbody></table></div>`;
}

Deno.serve(async (req) => {
  try {
    if (req.method !== "POST") return secureJson({ error: "Method not allowed" }, { status: 405 });
    const base44 = createClientFromRequest(req);

    let user = null;
    try { user = await base44.auth.me(); } catch (_) {}
    if (user && user.role !== "admin") return secureJson({ error: "Forbidden" }, { status: 403 });
    if (!user && !allowAnonymousAutomation(req)) return secureJson({ error: "Forbidden" }, { status: 403 });

    const [settings] = await base44.asServiceRole.entities.AdminSettings.list("-created_date", 1);
    const notificationEmail = settings?.lead_notification_email || Deno.env.get("ADMIN_NOTIFICATION_EMAIL") || Deno.env.get("ADMIN_EMAIL");
    if (!notificationEmail) return secureJson({ error: "No admin notification email configured. Set AdminSettings.lead_notification_email or ADMIN_NOTIFICATION_EMAIL secret." }, { status: 400 });

    const allLeads = await base44.asServiceRole.entities.Leads.list("-updated_date", LEAD_LIMIT);
    const now = Date.now();
    const dayMs = 86400000;
    const startOfToday = getPhoenixDayStart();
    const newToday = allLeads.filter((l) => new Date(l.created_date).getTime() >= startOfToday.getTime()).length;
    const hotLeads = allLeads.filter((l) => l.activation_priority === "Hot" && l.status !== "Booked" && l.status !== "Closed");
    const overdueFollowUp = allLeads.filter((l) => {
      const isActive = !["Booked", "Closed"].includes(l.status);
      const nextFollowUpAt = l.next_follow_up_at ? new Date(l.next_follow_up_at).getTime() : null;
      if (nextFollowUpAt) return isActive && nextFollowUpAt <= now;
      const noContact = !l.last_contacted_at || (now - new Date(l.last_contacted_at).getTime()) > dayMs;
      return isActive && noContact;
    });
    const replied = allLeads.filter((l) => l.status === "Replied");

    const hotRows = hotLeads.slice(0, 5).map((l) => `<tr><td style="padding:8px 10px;border-bottom:1px solid ${CS_EMAIL_THEME.border};">${csEmailEscape(l.full_name)}</td><td style="padding:8px 10px;border-bottom:1px solid ${CS_EMAIL_THEME.border};">${csEmailEscape(l.business_name)}</td><td style="padding:8px 10px;border-bottom:1px solid ${CS_EMAIL_THEME.border};">${csEmailEscape(l.status)}</td><td style="padding:8px 10px;border-bottom:1px solid ${CS_EMAIL_THEME.border};">${csEmailEscape(l.lead_score ?? 0)}</td></tr>`).join("");

    const metrics = `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:24px;border-collapse:collapse;"><tr>${metricCard("New Leads", newToday, "Created today")}${metricCard("Hot Leads", hotLeads.length, "Need outreach")}</tr><tr>${metricCard("Overdue", overdueFollowUp.length, "Follow-ups due")}${metricCard("Replied", replied.length, "Need qualification")}</tr></table>`;
    const body = `${metrics}${hotLeadTable(hotRows)}`;
    const html = csEmailShell({ badge: "Daily Digest", title: `Daily Lead Digest — ${formatPhoenixDate()}`, subtitle: "Your daily ClientSurge lead snapshot is ready.", body, logoUrl: csEmailLogoUrl(), footerTitle: "Daily lead digest", footerText: "Sent daily at 8am Arizona time. Manage leads in your admin dashboard." });

    const resendKey = Deno.env.get("RESEND_API_KEY");
    if (!resendKey) return secureJson({ error: "RESEND_API_KEY not set" }, { status: 500 });
    const fromEmail = settings?.resend_from_email || csEmailFrom("noreply@clientsurgesystems.com");

    const res = await resendFetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { Authorization: `Bearer ${resendKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({ from: fromEmail, to: notificationEmail, subject: `Daily Lead Digest — ${newToday} new, ${hotLeads.length} hot, ${overdueFollowUp.length} overdue`, html }),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      throw new Error(err?.message || `Resend error ${res.status}`);
    }

    return secureJson({ success: true, stats: { newToday, hot: hotLeads.length, overdue: overdueFollowUp.length, replied: replied.length } });
  } catch (error) {
    console.error("[sendDailyDigest] sendDailyDigest error:", error);
    return secureJson({ error: error.message }, { status: 500 });
  }
});